LLNL/RAJA

README.md
We only want to point people at the hosted documentation at software.llnl.gov
=> Remove confusing sphinx paragraph from the README

include/RAJA/exec-cuda/MemUtils_CUDA.hxx, include/RAJA/exec-cuda/reduce_cuda.hxx, include/RAJA/reducers.hxx, src/MemUtils_CUDA.cxx, test/unit-tests/GPUtests/CMakeLists.txt, test/unit-tests/GPUtests/ReduceMaxLoc.cxx, test/unit-tests/GPUtests/ReduceMinLoc.cxx
Single-pass CUDA reductions for min/maxloc. Algorithm uses the fast hardware atomicAdd(int) to keep track of blocks retired; last block finishes the reduction. Atomic updates are not used for the actual values or indices. GPU Unit tests ReduceMinLoc.cxx and ReduceMaxLoc.cxx show usage example.
=> Implement ReduceMinLoc, ReduceMaxLoc; added unit tests as well

include/RAJA/exec-cuda/forallN_cuda.hxx, test/unit-tests/GPUtests/Nested.cxx
Uses INT_MIN rather than -1 to represent out-of-bounds indices when
launching the CUDA forallN
=> Allow negative indices in RangeSegment

.clang-format, scripts/clang-format-all.py
This encodes a format that is as similar as I could seem to get clang-format to go to the style used in RAJA overall.  The only real difference is that it is more likely to pull template parameters and function arguments onto a single line when they fit in the 80-column limit than the manual style.
I suggest folks give this a try, and see if it's close enough to be made a standard tool for styling.  If there are any particular complaints, it's entirely possible they can be fixed.
=> adding a clang-format file to help style code

include/RAJA/exec-cuda/raja_cuda.hxx, include/RAJA/exec-cuda/reduce_cuda.hxx
Small code change, added static asserts testing 
1) That the block size is a power of two
2) That the block size is between 32 and 2048. 2048 is chosen randomly, feel free to propose changes
Reviews from either of @jonesholger or @davidbeckingsale ? You'll need to build CUDA, do a correctly sized reduction, and an incorrectly sized reduction to test. To remove the WIP tag we need to settle on a max block size
Note: code contributed by @trws
=> Added assertions to protect correct block sizes in CUDA reductions

cmake/SetupPackages.cmake
Fixes the '-DRAJA_TIMER=gettime' build.
@rhornung67, @keasler, does this version work for you?
=> fixing librt detecton for gettime timer

.pullapprove.yml
This adds a pullapprove configuration.  You can read the YAML for full details, but PRs will require two approvals from the group @ajkunen, @keasler, @rhornung67, and @trws (this is arbitrary and temporary, let me know who all should be on the list).  This system can also let us say one reviewer from a given group and one review from another to merge, so I'll be happy to set that up but I need to know what the preference is.
To use it, you can link through to pullapprove to approve or reject, or you can use a github comment to get the same effect.  I adjusted the approval regex to hit the common items, but you will need to have a line that starts with one of:
*  `:+1:` or `:thumbsup:` or the unicode equivalent thereto (:+1:)
*  `:shipit:` (:shipit:)
* Approved
* I approve
To reject, it …
=> adding pullapprove configuration

test/unit-tests/CPUtests/main-traversal.cxx
I think I missed this during rebase - we don't want to return 0 before checking how many tests pass.
=> Delete unnecessary return statement

cmake/SetupPackages.cmake, examples/CMakeLists.txt, examples/pi.cxx, test/unit/cpu/CMakeLists.txt
This is a set of hotfixes for build issues with the gtest integration that only showed up on odd environments.  Since a build with enable_cuda forces all including files to include cuda constructs, they only build with NVCC.  We really need to fix that.  Also, the gtest library needs to be built with the same ABI as the rest of raja, so it must be built with the same compilers. This version passes all CPU and GPU tests on rzhas.
=> hotfix for compilation issues with nvcc and the new test integration

host-configs/bgqos/clang_3_9_0.cmake, host-configs/bgqos/gcc_4_8_4.cmake, test/unit/cpu/CMakeLists.txt, test/unit/gpu/CMakeLists.txt
Switch to compiling each object only once, and only compile gpu Nested test when OpenMP is available.
=> fix nvcc test build

test/unit/cpu/CMakeLists.txt, test/unit/gpu/CMakeLists.txt
This address compiler warnings mentioned in #125 
Tests requiring nested functionality are only build when `-DRAJA_ENABLE_NESTED=On`
=> Add guards for RAJA_ENABLE_NESTED to tests

test/unit/cpu/CMakeLists.txt
The `scan-test` test was actually running the traversal tests.
=> Fixup copy-paste typo for scan-test

include/RAJA/foralln/Generic.hxx, include/RAJA/foralln/Tile.hxx
Template argument name PI may collide with common macro PI.
=> Rename template parameters to avoid name collision

src/CMakeLists.txt
Windows needs RUNTIME DESTINATION for .dll libraries to be installed.
=> Issue186 install on windows

include/RAJA/IndexValue.hxx, include/RAJA/foralln/Layout.hxx
Fixed IndexValue convertIndex function to correctly work using SFINAE
Fixed Layout::toIndices implementation... i think this got messed up during a refactor
=> foralln: fixed implementations of convertIndex and Layout::toIndicies

include/RAJA/internal/defines.hxx
Add include stdlib.h to fix compile issues. (abort, getenv)
=> Fix missing include stdlib.h

include/RAJA/index/IndexSet.hpp, include/RAJA/index/ListSegment.hpp, include/RAJA/index/RangeSegment.hpp, include/RAJA/pattern/scan.hpp, include/RAJA/policy/cilk/forall.hpp, include/RAJA/policy/cilk/reduce.hpp, include/RAJA/util/Layout.hpp, include/RAJA/util/OffsetLayout.hpp, include/RAJA/util/Operators.hpp, include/RAJA/util/PermutedLayout.hpp, include/RAJA/util/View.hpp
In addition to resolving the last `hxx` headers, this PR switches all instances of relative includes (e.g. within the same directory) to absolute path includes.
RFC: there is `"cycles.h"` defined under fault_tolerance which no longer exists -- what should we do about this?
=> [Bugfix] Repair additional headers

include/RAJA/internal/type_traits.hpp, include/RAJA/policy/PolicyBase.hpp, include/RAJA/policy/cilk/policy.hpp, include/RAJA/policy/cuda/policy.hpp, include/RAJA/policy/openmp/policy.hpp, include/RAJA/policy/sequential/policy.hpp, include/RAJA/policy/simd/policy.hpp, test/include/data_storage.hxx
**NOTE** this has been heavily updated and the text at the top is the most recent implementation
`PolicyBase` now defines different types of policies and types:
here's a proposed change that explicitly breaks apart policy, launch, and pattern. This would also make `Pattern`, `Policy` and `Launch` more friendly for user-facing logic :)
```cpp
enum class Policy {
undefined,
sequential,
simd,
openmp,
cuda,
cilk
};
enum class Launch {
undefined,
sync,
async
};
enum class Pattern {
undefined,
forall,
reduce,
taskgraph,
};
template <
Policy P = Policy::undefined,
Launch L = Launch::undefined,
Pattern Pat = Pattern::undefined>
struct PolicyBase {
static constexpr Policy policy = P;
static constexpr Launch launch = L;
static constexpr Pattern pattern = Pat;
};
template <typename Inner, typename …
```
=> [Enhancement] PolicyBase well-defined and corresponding type_traits

CMakeLists.txt, cmake/CompilerCompatibility.cmake, cmake/SetupCompilers.cmake, include/RAJA/internal/ForallNPolicy.hpp, include/RAJA/util/Layout.hpp, include/RAJA/util/Operators.hpp, include/RAJA/util/PermutedLayout.hpp, test/unit/CMakeLists.txt, test/unit/test-integral-limits.cxx
`numeric_limits` is great with host-only code, but breaks with GPU code. I hand-rolled limits for all integral types and floating-point types.
* Unsigned Integral types rely on the compiler masking appropriately
* Signed integral types use some bit hack magic -- I tested with numeric_limits before committing
* Floating-point types rely on `cfloat` and `{FLT,DBL,LDBL}_MAX`
I also threw in a fix for a massive warning dump with CUDA 8 on my arch box -- `operator()` within `ForallNPolicy` was not marked `RAJA_SUPPRESS_HD_WARN` (but is now). If this is intentional, I can revert it back.
=> [enhancement] Fix operator limits by removing `std::numeric_limits`

include/RAJA/index/IndexValue.hpp, include/RAJA/util/Layout.hpp, test/unit/test-layout.cxx
There may be some more refactoring to be done here, factoring out TypedView for example, but this adds a strongly typed Layout to assist with the kripke update.  It also modifies the strongly typed index types such that a reference can be taken to their enclosed Index_type value.
=> Add typed layout

include/RAJA/index/IndexSetUtils.hpp, include/RAJA/internal/IndexArray.hpp, include/RAJA/internal/rangelist_forall.hpp
As part of a test for something else I tried modularizing RAJA, turns out that's less hard than I thought, but these include issues popped out as part of the process.  By way of a side note, a compilation of a minimal test file using modules turned out to be about six times faster than the classic header model.
=> repair includes for headers, based on creation of a module-map for clang

include/RAJA/util/defines.hpp
This is the second attempt at this PR (trying to get Intel build to not error in CI). Trying a clean branch with the commits merged from @jeffhammond 's initial PR
Closes #263 
this was previously addressed by https://github.com/LLNL/RAJA/pull/231
but that used the C header.  subsequently, that change was undone.
this fix uses the correct C++ solution, which means `cstdlib` instead of
`stdlib.h` and prepending `getenv` and `abort` with `std::`
=> Add header and namespace for getenv and abort [updated]

CMakeLists.txt, include/RAJA/index/RangeSegment.hpp, include/RAJA/internal/Iterators.hpp, test/unit/cpu/CMakeLists.txt, test/unit/cpu/test-segments.cpp
The TypedRangeStrideSegment had some implementation issues that this PR aims to resolve:
1) didn't handle non-exact ending values correctly, such as  TypedRangeStrideSegment(1, 13, 3)
2) didn't handle negative strides at all, such as TypedRangeStrideSegment(10, 3, -1)
I've gotten this all working, at least sequentially. Still need to make sure it works with OMP/CUDA/etc.
=> Fixed wonkey logic in TypedRangeStrideSegment, added barrage of unit tests

test/unit/CMakeLists.txt, test/unit/cpu/CMakeLists.txt
Amazingly, the new IndexSet, Concepts, and Multipolicy *work*. I'll wait for a newer compiler instead of attempting to resolve the remaining tests, but there are only two tests we aren't running.
=> Enable all but two tests (Scan and Reductions) to MSVC CI

include/RAJA/internal/Iterators.hpp, test/unit/cpu/test-segments.cpp
The following loop wasn't working with negative strides: (and therefore forall wasn't working either)
for(auto i = segment.begin();i < segment.end();++i)
{ ... }
Since the operator< wasn't "direction" aware.
So I fixed the iterator to take stride direction into account, and also fixed the unit tests to properly detect this error.
=> Fixed strided_numeric_iterator to apply the stride sign to comparison operators

test/unit/test-timer.cpp
Save us all ~2 seconds per build, check both lower and upper bounds for time.
=> tweak the timer tests to be less noisy and faster

include/RAJA/internal/ForallNPolicy.hpp
The constructor of ForallN_BindFirstArg_HostDevice took body by value which caused an extra copy to be made.
This fixes the ReduceSumCUDA.indexset_aligned test. The current cuda reducers assume that the first copy in device code will be destroyed after running the lambda. The cuda reducers in #283 assume that their constructors and destructors are called in a nested fashion in device code.
=> Extra Copy in ForallN_BindFirstArg_HostDevice Constructor

test/CMakeLists.txt, test/integration/CMakeLists.txt, test/integration/chai/CMakeLists.txt, test/unit/CMakeLists.txt, test/unit/cpu/CMakeLists.txt, test/unit/cuda/CMakeLists.txt, test/unit/omp-target/CMakeLists.txt
Closes #298 
Instead of undoing all of the google-test refactor, this PR just updates the binary generation to it's previous state (one binary per test source file).
There are some performance implications with having the tests be separate binaries though -- on the order of 15% for compilation on `wiz` and 10% for execution.
=> Switch back to multiple test executables

cmake/SetupCompilers.cmake, cmake/SetupRajaConfig.cmake, include/RAJA/config.hpp.in, include/RAJA/internal/MemUtils_CPU.hpp, include/RAJA/policy/openmp/reduce.hpp, include/RAJA/policy/sequential/reduce.hpp, include/RAJA/policy/tbb/reduce.hpp
Thanks to @tepperly for reporting this one.  After moving the aligned allocation and free stuff out of implementation and into a header it's possible for the `#error` condition to come up in user code.  This PR makes them dependent on configuration time, rather than compile-time, parameters and adds a portable aligned allocation capability such that the error pragma is never needed.
=> remove compile-time error from memutils, add portable alligned allocator

cmake/SetupCompilers.cmake
Turns out nvcc is picky about host compilers for 14.  Rather than try and write out their actual check, especially since they haven't told us what it is, this just tries to use the dang flag with the configured host compiler and checks the result.
=> add an extra check before activating 14 on nvcc

test/unit/omp-target/CMakeLists.txt
A quick fix to remove older add_gtest method of adding unit tests
=> hotfix for CMakelists.txt for omp-target tests

test/integration/chai/chai-nested.cpp
When CHAI is enabled and OpenMP is not,  I just #ifdef the OpenMP policies in the unit tests to sequential.
=> Fixed CHAI+CUDA unit tests to compile without OpenMP enabled

include/RAJA/policy/openmp/target_reduce.hpp, test/unit/omp-target/test-reductions.cpp
Previously each thread started with this value leading to the wrong calculation, so kernels not using identity as the initial value would generate numeric errors. Oddly, the unit tests did not catch this, and was noticed later in the Perfsuite TRAP_INT kernel. 
Initial value is now deferred to the TargetReduce classes which now provide storage for initVal,finalVal (analogously for loc), and calculation is finalized in the get() call.
Note, that I believe omp-target reductions need some serious work, especially on the performance front. But, this is a necessary hotfix for correctness.
=> hotfix to properly handle initial value

include/RAJA/internal/LegacyCompatibility.hpp, include/RAJA/pattern/nested.hpp, include/RAJA/policy/cuda/forall.hpp, include/RAJA/policy/cuda/forallN.hpp, include/RAJA/policy/cuda/nested.hpp, include/RAJA/policy/cuda/policy.hpp, test/unit/nested.cpp
This enables nested::forall to use the cuda_thread_*_exec and related policies from forallN inside of a CudaCollapse clause.
I've got this running with one unit test off the bat... I've got to try and get more testing established, but I wanted to get some feedback before I went gonzo.
=> Initial implementation of the nested::Collapse for CUDA policies.

include/RAJA/policy/cuda/nested.hpp, test/unit/nested.cpp
Added a call to  RAJA::cuda::make_launch_body  in the CUDA executor to make sure the reducers work properly.
Added a few unit tests to ensure correctness
=> Fixed nested::forall to work with CUDA reducers

include/RAJA/policy/openmp/scan.hpp, scripts/travis_build_and_test.sh, test/unit/cpu/test-scan.cpp
Building manually on rzhasgpu with nvcc+gcc-4.9.3 failes test-scan.exe when running more than 1 thread.
I don't see this building just gcc-4.9.3 w/ openmp.
Just checking that our CI is running w/ threads.
=> Fix: OpenMP scans broken when num threads didn't match requested num threads

include/RAJA/policy/cuda/forall.hpp, include/camp/tuple.hpp
This was wreaking havoc with reductions.
Also, the cuda forall was doing an extra privatization copy by accident (was unnecessary).
The way camp::tuple was implemented, it accidentally forced a number of copy constructions of temporary objects.  This is a serious performance issue, and it completely broke reductions in the refactored nested::forall.
=> Fixed a number of excessive copies, mostly in camp::tuple.

include/RAJA/RAJA.hpp, include/RAJA/pattern/detail/forall.hpp, include/RAJA/pattern/nested.hpp, include/RAJA/pattern/nested/internal.hpp, include/RAJA/pattern/nested/tile.hpp, include/RAJA/policy/cuda/nested.hpp, include/RAJA/policy/openmp/reduce.hpp, include/RAJA/util/Layout.hpp, include/RAJA/util/OffsetLayout.hpp, include/RAJA/util/Operators.hpp, include/RAJA/util/Permutations.hpp, include/RAJA/util/PermutedLayout.hpp, include/RAJA/util/SoAArray.hpp, include/RAJA/util/SoAPtr.hpp, include/RAJA/util/Timer.hpp, include/RAJA/util/TypeConvert.hpp, include/RAJA/util/View.hpp, include/RAJA/util/align.hpp, include/RAJA/util/basic_mempool.hpp, include/RAJA/util/camp_aliases.hpp, include/RAJA/util/chai_support.hpp, include/RAJA/util/defines.hpp, include/RAJA/util/mutex.hpp, include/RAJA/util/types.hpp, test/unit/nested.cpp, test/unit/test-layout.cpp
The new header file contains aliases in the RAJA namespace for
camp types used in our tests and examples. Others should be added
when other camp types bleed through the RAJA API when new tests
and examples are built.
Also, fixed copyright info in several files. Some were missing copyright
and license info. Some still had the long form that we had originally.
=> Added header file to hold camp aliases and fixed copyright statments.

appveyor.yml, include/RAJA/RAJA.hpp, include/RAJA/pattern/nested.hpp, include/RAJA/pattern/nested/internal.hpp, include/RAJA/pattern/nested/tile.hpp, include/RAJA/policy/cuda/nested.hpp, test/unit/cpu/test-nested.cpp, test/unit/nested.cpp
I eliminated the TypedFor, in favor of using the TypedRangeSegment to set the loop index types.  This makes calculating the loop types MUCH easier, gets index types out of the policies, and should help pave the way for more complex nested::forall development.
Also, I've changed variable names in the nested::forall internal data structures... mostly just expanding things like pt and st to policy_tuple and segment_tuple.
=> Eliminated nested::TypeFor, changed variable names for readability

.travis.yml, include/RAJA/policy/cuda/nested.hpp, test/unit/nested.cpp
Also, changed a unit test to tickle this issue
=> Fixed bug in nested::forall CUDA Collapse when using strongly typed indices

include/RAJA/index/IndexSet.hpp
If a compilation unit doesn't reference IndexSet, the deprecation warning on the IndexSet type alias makes the Intel compiler bark at you.
I switched IndexSet to typedef instead of type alias.
This seems to make the Intel compiler happy.
=> Fixed deprecation warning for Intel compiler

include/RAJA/index/RangeSegment.hpp, test/unit/cpu/test-segments.cpp
Remove narrowing errors in TypedRangeStrideSegment constructor when used with types smaller than Index_type.
=> Remove narrowing errors

include/RAJA/index/RangeSegment.hpp, include/RAJA/internal/Iterators.hpp, test/unit/nested.cpp
TypedRangeStrideSegment::slice() didn't actually compile, but we didn't notice since it wasn't being unit tested.
Also, logic needed some fix up in order to clamp to m_end, like TypeRangeSegment.
Also TypedRangeStrideSegment had no copy assignment operator, also used in Tile policies.
=> Fixed TypedRangeStrideSegment::slice, used for Tile policies.

include/RAJA/index/IndexSetBuilders.hpp, src/LockFreeIndexSetBuilders.cpp
These were missed when TypedIndexSet was created.
=> Fix function signatures for IndexSet builders

examples/CMakeLists.txt
We have an email submitted bug from Ron Green (@greenrongreen) on our email list, we're naming an example executable ExampleName.cpp rather than ExampleName.
=> Fixed naming of example executable

include/RAJA/policy/atomic_builtin.hpp
Fixes #447 
Basically just cut out if the action of the atomic can't have an effect.
=> optimize builtin min/max atomics

include/RAJA/util/View.hpp, test/unit/cuda/test-forall-view.cpp
We found a bug when views are used in the device with offset layouts. In particular the generated copy constructor does not actually copy-construct the object.
The follows compilers generate run time errors :
CUDA 8, 9.0.176, 9.0.184, 9.1.76, 9.1.85 .
We are able to fix the bug by specifying the copy constructor. An additional unit test was added to test-cuda-forall-view.cpp to test for correct behavior.
=> Fixes bug to view with offset layout

include/RAJA/policy/cuda/reduce.hpp, test/unit/cuda/test-forall-view.cpp, test/unit/cuda/test-forall.cpp, test/unit/cuda/test-nested-strided.cpp, test/unit/cuda/test-nested.cpp, test/unit/cuda/test-reduce-loc.cpp, test/unit/cuda/test-reduce-max.cpp, test/unit/cuda/test-reduce-min.cpp, test/unit/cuda/test-reduce-sum.cpp, test/unit/cuda/test-synchronize.cpp
This fixes Raja cuda reducers to work in host device lambdas.
This pull request changes the cuda tests to use both device and  host device lambdas.
The bug was caused by reading uninitialized memory. The RAJA cuda reducers expected the gpu to write to the memory allocated for the reduction result from the device. However host device lambdas have separate copies of the captured values for the host and the device. So both copies of the reducer allocate space for the reduced value from the gpu, but no value is written to the memory allocated by the host lambda copy of the reducer. When this memory is read it causes the final result to be garbage.
=> Fix RAJA cuda reducers with host device lambdas

include/camp/tuple.hpp
Was causing issues with some compilers when the storage type had no data memebers
This appears to fix things on rzhasgpu.llnl.gov with gcc 4.9.3 + CUDA 9.1, and with clang 4.0.0 + CUDA 9.1.
=> Fixed initialization of tuple_storage to use (...) instead of {...}

include/RAJA/pattern/kernel/For.hpp
Having the extra semicolon caused warnings to spew out under certain compiler settings.
=> Removed extra semicolon

examples/cpu-shmem-ltimes.cpp, examples/omp-target-ltimes.cpp
Removed the Simd policy on the top level loops of the l-times example.
=> Ltimes build fix

include/RAJA/policy/openmp/region.hpp
Fixed the parallel region in raja/include/RAJA/policy/openmp/region.hpp to keep current XLC compilers from generating incorrect code and failing tests. Very simple change modifying
#pragma omp parallel
body();
to
#pragma omp parallel
{
body();
}
=> fixed parallel region in OpenMP region.hpp

include/RAJA/pattern/kernel/Conditional.hpp, include/RAJA/pattern/kernel/For.hpp, include/RAJA/pattern/kernel/Tile.hpp, include/RAJA/pattern/kernel/internal.hpp, include/RAJA/policy/cuda/kernel/For.hpp, include/RAJA/policy/cuda/kernel/Tile.hpp, test/unit/test-kernel.cpp
Add support for getting iteration and tile indices via parameters.
Variant of For and Tile statements that set a member of the param tuple to the iteration or tile index respectively.
- RAJA::statement::ForICount<Segment#, RAJA::statement::Param<#>, exec, ...>
- RAJA::statement::TileTCount<Segment#, RAJA::statement::Param<#>, exec, ...>
=> Iteration and Tile index/count

.travis.yml
This is what caused the issue with PR #549, since forks don't have the encrypted key, they were having both DO_BUILD and DO_TEST set to no.
=> build and test on forks that don't have intel key

CMakeLists.txt
This squashes an annoying warning you get during the CMake configure step
=> Only set RAJA_LOADED where there actually is a PARENT_SCOPE

include/RAJA/policy/cuda/kernel/Conditional.hpp, include/RAJA/policy/cuda/kernel/CudaKernel.hpp, include/RAJA/policy/cuda/kernel/For.hpp, include/RAJA/policy/cuda/kernel/ForICount.hpp, include/RAJA/policy/cuda/kernel/Hyperplane.hpp, include/RAJA/policy/cuda/kernel/InitLocalMem.hpp, include/RAJA/policy/cuda/kernel/Lambda.hpp, include/RAJA/policy/cuda/kernel/Sync.hpp, include/RAJA/policy/cuda/kernel/Tile.hpp, include/RAJA/policy/cuda/kernel/TileTCount.hpp, include/RAJA/policy/cuda/kernel/internal.hpp, include/RAJA/policy/cuda/policy.hpp, test/unit/test-kernel.cpp
Changed plumbing in RAJA::kernel to only mask off threads that are out of bounds at the Lambda invokation.
This allows threads that are masked off to still participate in syncthreads, etc., which was causing hangs with the NVidia V100's.
Also, it allowed the elimination of the cuda_seq_syncthreads_exec policy.
=> Changed plumbing in RAJA::kernel to defer masking off threads until lambda is called

docs/sphinx/user_guide/feature/policies.rst
Left out a couple documentation fixes from before. Replaced NUMTEAMS with ThreadsPerTeam, and clarified explanation.
=> OMP target documentation fix.

include/RAJA/policy/cuda/kernel/Sync.hpp
Tests with __syncwarp were failing to compile with CUDA 8.0. Added NOP alternative to __syncwarp.
=> __syncwarp NOP alternative

include/RAJA/config.hpp.in
Removes warnings generated when using nvcc + xlC
=> Reworked align hint macro logic when using xlc + nvcc

include/RAJA/index/IndexValue.hpp, include/RAJA/index/RangeSegment.hpp, include/RAJA/internal/Iterators.hpp
Mostly fixes for defaults for difference_type, and remove accidental type conversions (like assuming Index_type)
Had to add a helper class to strip strongly typed indices down to their value type.
Reverted some of the changes to TypedRangeStrideSegment to fix correctness issues.
=> Fixed TypedRangeSegment, TypedRangeStrideSegment

include/RAJA/RAJA.hpp, include/RAJA/policy/cuda/kernel/For.hpp, include/RAJA/policy/cuda/kernel/ForICount.hpp, include/RAJA/policy/cuda/kernel/Tile.hpp, include/RAJA/policy/cuda/kernel/TileTCount.hpp, include/RAJA/policy/cuda/policy.hpp, include/RAJA/util/BitMask.hpp, test/unit/test-kernel.cpp
Adding missing executors for existing CUDA warp/thread policies, and bitmasked policies that allow dividing up a warp or block based on bitmasks.
Also, added a bunch of unit tests
=>  CUDA: Adding missing executors and bitmasked policies

include/RAJA/index/ListSegment.hpp, include/RAJA/policy/cuda.hpp
By adding a few checks, this PR enables users to maintain one build of RAJA and be compatible with strict device code and CUDA code. This was motivated by an application which compiled packages which depended on RAJA with both nvcc and host compilers.
=> Guards for cuda enabled RAJA

include/RAJA/policy/cuda/kernel/CudaKernel.hpp, test/unit/test-kernel.cpp
Pick the correct global function used with cuda kernel policies.
Previously the global function used with unknown num_threads was
always being used.
=> Use CudaKernelLauncherFixed with compile-time num_threads

docs/sphinx/user_guide/feature/atomic.rst, docs/sphinx/user_guide/feature/policies.rst, docs/sphinx/user_guide/tutorial/atomic_binning.rst, examples/pi-reduce_vs_atomic.cpp, examples/tut_atomic-binning.cpp, include/RAJA/pattern/atomic.hpp, include/RAJA/policy/atomic_auto.hpp, include/RAJA/policy/atomic_builtin.hpp, include/RAJA/policy/cuda/atomic.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/loop/atomic.hpp, include/RAJA/policy/openmp/atomic.hpp, include/RAJA/policy/sequential/atomic.hpp, include/RAJA/util/LocalArray.hpp, include/RAJA/util/View.hpp, test/unit/test-atomic-ref-auto.cpp, test/unit/test-atomic-ref.cpp, test/unit/test-atomic-ref.hpp, test/unit/test-atomic.cpp, test/unit/test-kernel.cpp, test/unit/test-sharedmem.cpp
This makes use of RAJA atomic operations consistent with other RAJA capabilities; e.g., reductions, scans, etc.
I discussed with several code teams and all are OK with this.
=> Removed 'atomic' namespace.

include/RAJA/config.hpp.in, include/RAJA/util/macros.hpp
This implements a more portable version of the pragma macro that we're trying to promote in all of our code's dependencies.
=> More portable pragma macro. (courtesy of Al Nichols)

exercises/tutorial_halfday/ex1_vector-addition.cpp, exercises/tutorial_halfday/ex1_vector-addition_solution.cpp
Fix a small typo in the first example's output.
Also removes some end-of-line white spaces.
=> Example 1: Fix Typo

host-configs/lc-builds/blueos/pgi_X.cmake, scripts/lc-builds/blueos_pgi19.7.sh
Adding PGI 19.7 compilation scripts, with their optimization flags. The following tests fail due to a double free somewhere:
test-atomic-ref
test-atomic-ref-auto
=> PGI compilation scripts.

include/RAJA/policy/openmp_target/forall.hpp
When running Polybench_ADI and Polybench_GESUMMV, RAJA OpenMP Target seg faults when the thread_limit(tperteam) clause does not match the number of thread iterations. Removing the clause staves off the "Warp Illegal Address" errors and allows them to run to completion, albeit with faulty checksums. A single-file non-RAJA reproducer is in the works, but it is difficult to reproduce in a non-RAJA environment. Will iterate with Johann and Roy on this (separately from this PR).
=> Fix for seg fault in OMP Target when running PerfSuite. 

host-configs/lc-builds/blueos/nvcc_xl_2019_X.cmake, host-configs/lc-builds/blueos/xl_2019_X.cmake, include/RAJA/policy/openmp_target/forall.hpp
Added OMP Target warning suppression for "can't inline" and "nostrict -O3". Macro'ed iterables in target forall_impl's for clarity.
=> Suppress omp target warnings and cleaned up forall_impl.

LICENSE, NOTICE, README.md, RELEASE
- This PR is a minor documentation fix
- enables GitHub to automatically pick up license information and show it in the top banner of the project home page.
=> Fix files so GitHub automatically picks up license and shows in banner.

include/RAJA/pattern/kernel/internal.hpp, include/RAJA/policy/cuda/kernel/Sync.hpp
Privatized the CudaSyncThreads and Warp constructors to prevent misuse in lambdas.
=> Prevent user from declaring non-RAJA-policy CudaSyncs.

docs/style_guide.md, examples/tut_indexset-segments.cpp, examples/tut_vertexsum-coloring.cpp, exercises/tutorial_halfday/ex3_colored-indexset.cpp, exercises/tutorial_halfday/ex3_colored-indexset_solution.cpp, include/RAJA/index/IndexSet.hpp
- This PR is removes a deprecated feature. It may require minor RAJA usage changes to user code, depending on how they use RAJA IndexSets.
=> Remove deprecated IndexSet type alias and references to it.

include/RAJA/util/Registry.hpp, scripts/lc-builds/toss3_clang9.0.0.sh
- This PR converts remaining typedefs to using directives. (RAJA-184 JIRA issue)
- It also adds a build script for toss3 clang9 compiler.
=> Rm typedef

include/RAJA/pattern/forall.hpp, test/integration/CMakeLists.txt, test/integration/counter.hpp, test/integration/plugin_for_test.cpp, test/integration/test_plugin.cpp
This addresses an issue where plugins can be triggered multiple times
- Fixes #691 
- Modifies one `RAJA::forall` to call `wrap::forall` internally, rather than the generic `forall` again.
- Adds a test to ensure this won't happen again.
=> Ensure foralls always call wrap::forall

include/RAJA/index/IndexValue.hpp, test/unit/index/test-indexvalue.cpp
- Fixes unused-loc-typedef warning with clang generated by RAJA_INDEX_VALUE_T macro in IndexValue.hpp
- Replaces tabs with spaces in related IndexValue files
=> Fixing clang unused-loc-typedef warning

include/RAJA/policy/cuda/kernel/CudaKernel.hpp
- This PR improves caching of cuda occupancy calculator results in the CudaKernel launcher.
=> Improving cache use in CudaKernel launcher

include/RAJA/util/plugins.hpp
- This PR is a feature, that makes the two functions that call plugins `noexcept`
=> Make plugin caller functions noexcept

include/RAJA/pattern/detail/reduce.hpp, scripts/lc-builds/corona_hipcc.sh
- Fixes build failure of nvcc10+gcc7.3.1. Compiler was unable to modify ValueLoc operator= with RAJA_HOST_DEVICE. Now, uses default constructors for nvcc > 9.2 and HIP.
- Adds HIP build script for Corona.
=> HIP Constructor Fix

docs/sphinx/user_guide/tutorial/permuted-layout.rst
- This PR fixes a documentation bug where sphinx was pointing at the wrong code section.
=> Fixed documentation bug.

test/unit/atomic/test-atomic-ref-accessors.cpp, test/unit/atomic/test-atomic-ref-addsub.cpp, test/unit/atomic/test-atomic-ref-bitwise.cpp, test/unit/atomic/test-atomic-ref-constructor.cpp, test/unit/atomic/test-atomic-ref-exchanges.cpp, test/unit/atomic/test-atomic-ref-minmax.cpp
- This PR is bugfixin test/reorg.
- Changes CUDA_ test instantiations to GPU_ in test/unit/atomic.
=> Small fix for GPU_TYPED_TEST.

cmake/SetupCompilers.cmake, include/RAJA/RAJA.hpp, include/RAJA/pattern/detail/reduce.hpp, include/RAJA/policy/atomic_builtin.hpp
- Removes RAJA_HOST_DEVICE from defaulted constructors to prevent NVCC warnings.
=> Removed RAJA_HOST_DEVICE modifier from defaulted constructors.

CMakeLists.txt
At the request of a code team, make an un-built external camp usable.  For an external but installed camp, add the prefix to module-path, use the same prefix, or set camp_DIR to the location of the installed campConfig.cmake.
=> add EXTERNAL_CAMP_SOURCE_DIR option to use camp from source outside RAJA

include/RAJA/index/IndexSet.hpp, include/RAJA/util/Operators.hpp
For some reason these were failing under a specific compiler as being
missing unless fully qualified.
This is a bugfix for xlc++.
=> fully qualify _requires and SpecializationOf

test/unit/cuda/test-reduce-randloc.cpp, test/unit/cuda/test-reduce-tupleloc.cpp, test/unit/hip/test-reduce-randloc.cpp, test/unit/hip/test-reduce-tupleloc.cpp
- This PR is a bug fix.
- Mohammed Nafees at NVIDIA found that although the tuple tests pass, they fail when run under cuda-memcheck.
- Fixes this issue: the problem was that nvcc did not properly translate a "this->" to a member variable. This is solved by creating a local variable which points to the member.
- Also corrected some return casts.
=> Fix for CUDA memcheck failures in tuple tests.

examples/tut_scan.cpp, include/RAJA/policy/openmp_target/forall.hpp, test/unit/cpu/test-scan.cpp, test/unit/omp-target/test-nested-reduce.cpp, test/unit/omp-target/test-reduce-tuplemaxloc.cpp, test/unit/omp-target/test-reduce-tupleminloc.cpp, test/unit/omp-target/test-reductions.cpp
- fixes build problems for openmp offlload on current clang
- fixes reductions on clang
- random not in use for scan tests because of a bug in libc++ headers
=> omp-target: repair omp-target backend for current clang

include/RAJA/pattern/detail/reduce.hpp
- Updates rocPRIM submodule
- Updates macro guard around ValueLoc constructors so that HIP is not using defaulted ones.
=> Updates to HIP 

test/unit/index/test-rangesegment.cpp, test/unit/index/test-rangestridesegment.cpp
Removes warnings when compiling RangeSegment/StrideSegment tests with CUDA.
Fixes RangeSegment test so it passes when compiling with HIP.
=> RangeSegment/StrideSegment test warning/failure on CUDA/HIP

include/RAJA/policy/openmp/scan.hpp
Use the loop scan implementation instead of the sequential scan
implementation in the openmp policy
- Modifies the openmp scan implementation
=> Use loop scan in openmp scan impl

include/RAJA/policy/cuda/kernel/For.hpp, include/RAJA/policy/cuda/kernel/ForICount.hpp, include/RAJA/policy/cuda/kernel/Tile.hpp, include/RAJA/policy/cuda/kernel/TileTCount.hpp, include/RAJA/policy/hip/kernel/For.hpp, include/RAJA/policy/hip/kernel/ForICount.hpp, include/RAJA/policy/hip/kernel/Tile.hpp, include/RAJA/policy/hip/kernel/TileTCount.hpp, include/RAJA/policy/hip/policy.hpp, test/unit/test-kernel-lambda-args.cpp, test/unit/test-sharedmem.cpp
- This PR is adds full block direct support in kernel
- Fixes #744 
- Adds block_direct support for cuda and hip kernel statements For, ForIcount, Tile, and TileTcount
Deficiencies:
- ForIcount tests
- TileTcount tests
=> Full block direct support

include/RAJA/policy/cuda/atomic.hpp, include/RAJA/policy/hip/atomic.hpp, test/unit/test-atomic.cpp
Support cuda atomicExchange in the same manner as other cuda atomics.
Add test for atomicExchange and atomicCAS.
- Fixes atomicExch\<cuda\>(double)
- Fixes atomicExch\<hip\>(double)
=> Fix Cuda atomicExchange

include/RAJA/policy/cuda/atomic.hpp, include/RAJA/policy/hip/atomic.hpp, test/functional/CMakeLists.txt, test/functional/atomic/CMakeLists.txt, test/functional/atomic/test-atomic-forall-basic.cpp, test/functional/atomic/test-atomic-forall-basic.hpp, test/functional/atomic/test-atomic-forall-view.cpp, test/functional/atomic/test-atomic-forall-view.hpp, test/functional/atomic/test-atomic-ref-forall-math-auto.cpp, test/functional/atomic/test-atomic-ref-forall-math.cpp, test/functional/atomic/test-atomic-ref-forall-math.hpp, test/functional/atomic/test-atomic-ref-forall-other-auto.cpp, test/functional/atomic/test-atomic-ref-forall-other.cpp, test/functional/atomic/test-atomic-ref-forall-other.hpp, test/include/RAJA_value_params.hpp, test/unit/atomic/test-atomic-ref-accessors.cpp, test/unit/atomic/test-atomic-ref-addsub.cpp, test/unit/atomic/test-atomic-ref-bitwise.cpp, test/unit/atomic/test-atomic-ref-constructor.cpp, test/unit/atomic/test-atomic-ref-exchanges.cpp, test/unit/atomic/test-atomic-ref-minmax.cpp
- This PR re-organizes the old atomic tests into the functional test directory.
- Fixes unit/atomic/ tests for HIP.
- Splits old tests into slightly smaller chunks.
- Separates test instantiation in *.cpp files. This uses existing function templates to control test type combinatorial explosion, and AVOIDS template parameterization.
- TODO: Split -other- tests further.
- TODO: Add HIP tests.
On 12/17/2019, we discussed the design ideas:
1. Parameterized functional tests. Need to list every combination of test parameters.
2. Function templated functional tests (non-parameterized). Can avoid lists of test params, but need hierarchy of test function templates (see *.cpp files).
This PR implements 2, and we should discuss whether this is the right course for our …
=> Functional Tests for Old Atomics

include/RAJA/config.hpp.in
msvc does not support not as an alternative to ! in the preprocessor
- Fixes a compiler warning from msvc
=> Workaround msvc not supporting not

test/functional/atomic/test-atomic-forall-basic.cpp, test/functional/atomic/test-atomic-forall-basic.hpp, test/unit/util/test-span.hpp
- This PR is a bug fix
- Fixes atomic/functional Gtest CASE warning (converted to SUITE).
- Fixes XL span test compilation error. XL cannot compile a new'ed array with initializer list.
=> Fix Gtest warning and XL span test compilation error.

include/RAJA/pattern/detail/reduce.hpp
This PR gets rid of host device warnings when using `RAJA::ReduceMin::min()` and `RAJA::ReduceMax::max()` in a kernel.
Relevant to LLNL/Axom#174.
[Link to warning messages](https://github.com/LLNL/axom/pull/156#issuecomment-589899148)
=> Remove Reduce min and max CUDA host device warnings

test/unit/index/test-rangesegment.cpp, test/unit/index/test-rangestridesegment.cpp
- Modifies RangeSegment and RangeStrideSegment Unit tests to call negative tests through SFINAE functions.
- Cleans up ifdef calls within RSeg and RStridedSeg Unit tests.
- Fixes warnings that are generated by sign changes when unsigned types are tested, warnings were generating when compiling on travis with intel compilers.
=> Range(Strided)Segment Unit Test Warnings on Intel

include/RAJA/policy/openmp_target/forall.hpp
- makes the two openmp-target policies consistent, along with a camp patch fixing the new forall tests for openmp target
=> fix pointer translation issue in openmp_target policy

test/functional/forall/atomic-view/tests/test-forall-atomic-view.hpp, test/functional/forall/atomic/test-forall-atomic-basic-cuda.cpp, test/functional/forall/atomic/test-forall-atomic-basic-hip.cpp, test/functional/forall/atomic/test-forall-atomic-basic-openmp-target.cpp, test/functional/forall/atomic/test-forall-atomic-basic-openmp.cpp, test/functional/forall/atomic/test-forall-atomic-basic-seq.cpp, test/functional/forall/atomic/tests/test-forall-atomic-basic.hpp, test/functional/forall/test-forall-atomic-utils.hpp
- This PR is a refactoring of the atomic forall test
- Adds simple TypedRangeStrideSegment and TypedListSegment to forall-atomic-basic tests.
- Adds framework for TypedIndexSet, but not activated due to incompatible execution policies. This can be removed from the PR if so desired.
=> Segments for Atomic Functional Forall Tests

host-configs/lc-builds/blueos/xl_2020_X.cmake, scripts/lc-builds/blueos_xl-2020.03.18.sh, scripts/lc-builds/blueos_xl-2020.03.18_omptarget.sh, test/functional/forall/indexset-view/test-forall-indexset-view-openmp-target.cpp, test/functional/forall/indexset/test-forall-indexset-openmp-target.cpp, test/unit/reducer/tests/test-reducer-constructors.hpp, test/unit/reducer/tests/test-reducer-reset.hpp
- Updates CAMP version to register-singleton branch to fix OpenMP target compilation. New OpenMP target tests will still segfault due to camp::resources:omp not mapping correctly.
- Various other fixes:
- Use correct OpenMPTargetResource for indexset tests.
- Use updated REGISTER_TEST_SUITE in reducer unit tests.
- Add xl/2020.03.18 build scripts for omp-target testing.
=> CAMP update to register-singleton branch for omptarget correctness

include/RAJA/pattern/detail/reduce.hpp, include/RAJA/policy/openmp_target/reduce.hpp, test/functional/forall/reduce-sanity/tests/test-forall-reduce-sanity-max.hpp, test/functional/forall/reduce-sanity/tests/test-forall-reduce-sanity-maxloc.hpp, test/functional/forall/reduce-sanity/tests/test-forall-reduce-sanity-min.hpp, test/functional/forall/reduce-sanity/tests/test-forall-reduce-sanity-minloc.hpp, test/functional/forall/reduce-sanity/tests/test-forall-reduce-sanity-sum.hpp, test/old-tests/unit/cpu/test-reductions.cpp, test/unit/reducer/CMakeLists.txt, test/unit/reducer/test-reducer-reset-openmp-target.cpp
- This PR adds the reset method to the omp target reduce class. 
Folks, in general I had hard time building all of RAJA with omp target. I had to choose which files to build to manage build times. 
Additionally, using OpenMPTargetResourceList led to segfaults, I had to use HostResourceList to test this code.
=> Add reset to omp target reducer

docs/CMakeLists.txt, docs/doxygen/CMakeLists.txt, docs/sphinx/user_guide/CMakeLists.txt
- Renames the "docs" cmake target to "raja-docs" to avoid target conflicts
=> Rename docs target

CMakeLists.txt
- Checks if camp is already a cmake target before trying to use an external camp or the camp submodule
- Fixes issue #829
=> Allow using imported camp cmake target

include/RAJA/pattern/kernel/internal/Statement.hpp
All of our kernel statements that take enclosing statements, except
reduction, really need those enclosing statements.  After helping Will
debug some kernel shared memory code this morning, we worked out what
seems like a surprisingly nice way to catch most of this class of
errors. Everywhere we have a statement that either doesn't need or can't
take nested statements, it uses camp::nil as the policy, so this checks
for either camp::nil as the policy or at least one nested statement.
All of our tests in raja compile and run correctly with this in there,
but if I add say `statement::For<0, seq_exec>,` to a kernel policy it
errors out with this.  Same for if I put in an `InitSharedMem` and
forget to nest the rest of the policy (or at least something) under
it.
We might be able to go …
=> add kernel statement sanity test

README.md
- Fixes apparent spelling mistake on line 81 of the README
=> Correct spelling of portable in README/User Guide

test/include/RAJA_test-forall-execpol.hpp
- This PR adjusts the OpenMP exec policies in our forall tests. 
- Previous use of 'omp_for_*' policies was running all iterations on thread zero since no openmp parallel region was created. Probably not what we want to test.
=> Adjust forall execpols to exercise openmp stuff properly.

include/RAJA/pattern/kernel/internal/LoopData.hpp
- Modifies/refactors LoopData to be able to be constructed from parts on the device
- Fixes the tuple copy constructor warning issue for the segment tuple of the LoopData object by making the initial constructor host/device, which causes the copy constructor to generate appropriately
- Removes slightly odd, possibly dangerous, "similar" LoopData copy construction, since we have no cases of assigning different but similar LoopData objects this way.
I should note, it seems as though this is an entirely RAJA-side fix.  There's an alternate method we could use to address this, but it would increase compile time for all usages of the tuple, where this should be a smaller increase only for the LoopData class.
=> work around nvcc tuple copy constructor generation bug

include/RAJA/util/PluginLinker.hpp
Add RAJA namespace to pluginLinker to avoid collision with CHAI.
This is needed because anonymous namespaces in headers are all the same for the same source file.
Not that I am using anonymous_RAJA to avoid potential conflicts between ::RAJA and ::\<anonymous\>::RAJA, and am open to other suggestions.
=> Add namespace to pluginLinker

include/RAJA/index/ListSegment.hpp, include/RAJA/util/concepts.hpp
-Uses explicit namespaces as it simplifies integrating RAJA in build systems. 
Note this is unexpected as  using namespace ``camp::resources;`` was defined within scope.
=> Use explicit CAMP namespace names 

examples/raja-teams.cpp, include/RAJA/pattern/teams/teams_sequential.hpp
- This PR squashes warnings in the raja teams implementation code and example for CPU builds.
=> Squash compiler warnings for CPU builds

include/RAJA/pattern/WorkGroup/WorkStruct.hpp
- Fixes compile issue where std::max_align_t is not defined.
=> Add missing header for max_align_t

docs/sphinx/user_guide/feature/view.rst, include/RAJA/util/View.hpp, test/unit/view-layout/test-multiview.cpp
- This PR is a bugfix:
- Allows MultiView to work with strongly typed indices. Addresses issue https://github.com/LLNL/RAJA/issues/881.
=> Fix for strongly typed indices with MultiView

include/RAJA/util/View.hpp, test/unit/view-layout/test-multiview.cpp
- This PR is an update:
- Modifies MultiView to allow better CHAI integration. The compiler has difficulty deducing the non-const version of the array-of-pointers in MultiView when a CHAI::ManagedArray is the set of pointers. Allowing a custom non-const type to be passed in as a template parameter resolves this, while the default remains the same cv-removed type as before. Following this PR, there will be a corresponding CHAI PR uses this ability.
=> MultiView CHAI Integration

include/RAJA/index/IndexValue.hpp, include/RAJA/index/RangeSegment.hpp, include/RAJA/internal/Iterators.hpp, include/RAJA/pattern/detail/reduce.hpp, include/RAJA/util/Layout.hpp, include/RAJA/util/View.hpp, scripts/lc-builds/blueos_clang-ibm-2019.10.03_omptarget.sh, scripts/lc-builds/blueos_xl-2020.06.25.sh, scripts/lc-builds/blueos_xl-2020.06.25_omptarget.sh, scripts/lc-builds/toss3_clang9.0.0.sh, test/functional/forall/segment-view/tests/test-forall-ListSegmentView.hpp
This PR makes View, TypedRange[Stride]Segment, and [strided_]numeric_iterator trivially copyable.  It may be worth adding a check into a test file somewhere to check the type trait to make sure this is true all the time, but for now this should solve many of the warnings @rhornung67 was getting with target offload.
=> make common iterable and view types trivially copyable

docs/sphinx/user_guide/feature/policies.rst
The cuda/hip policy table does not render in the current version of the documentation. This PR fixes a misaligned entry in the cuda/hip policy table so that it renders.
=> docs: fix alignment in cuda/hip policy table

scripts/uberenv/packages/raja/package.py
- Update the local "copy" of RAJA Spack package to reflect changes in Spack.
The local copy of RAJA Spack package is used to experiment with future changes in the official RAJA Spack package.
That means that it is totally optional to have a local copy, and should only happen when needed. The changes should be updated to Spack asap.
There are currently new changes in the local copy, due to the recent introduction of Uberenv in the CI on Gitlab.
These changes will be submitted to Spack soon. They should first be reviewed here, and are tested as part of RAJA CI on Gitlab.
=> Update local spack package

docs/sphinx/user_guide/feature/policies.rst, include/RAJA/policy/cuda/atomic.hpp, include/RAJA/policy/hip/atomic.hpp, test/functional/forall/CMakeLists.txt, test/functional/forall/atomic-view/tests/test-forall-AtomicMultiView.hpp, test/include/RAJA_test-atomicpol.hpp, test/unit/atomic/test-atomic-ref.hpp
Add host implemention of hip atomics to match cuda implementation.
Note this is needed because usage of the hip atomics in so host device contexts fails to compile.
Added the gpu atomic explicit policies to the functional tests to test device side and host side functionality.
- Fixes ability to use hip atomics
=> Add host implemention of hip atomics

include/RAJA/pattern/WorkGroup/Vtable.hpp, include/RAJA/pattern/WorkGroup/WorkRunner.hpp, include/RAJA/pattern/WorkGroup/WorkStruct.hpp, include/RAJA/policy/cuda/WorkGroup/Vtable.hpp, include/RAJA/policy/cuda/WorkGroup/WorkRunner.hpp, include/RAJA/policy/hip/WorkGroup/Vtable.hpp, include/RAJA/policy/hip/WorkGroup/WorkRunner.hpp, test/unit/workgroup/tests/test-workgroup-Vtable.hpp, test/unit/workgroup/tests/test-workgroup-WorkStorage.hpp
Reduce collisions during device linking of function signatures used in WorkGroup cuda unordered policies.
- Modifies/refactors the WorkGroup device function signatures to avoid collisions during device linking.
- Specifically adds information from the WorkGroup policy like the number of threads per block.
=> Improve WorkGroup function signatures

include/RAJA/policy/hip/MemUtils_HIP.hpp, include/RAJA/policy/hip/WorkGroup/WorkRunner.hpp, include/RAJA/policy/hip/forall.hpp, include/RAJA/policy/hip/kernel/HipKernel.hpp
Update hip launch wrapper and use consistently when launching kernels in hip backend.
- Modifies/refactors hip kernel launches
=> Update hip launch wrapper

examples/tut_halo-exchange.cpp
Remove an extra template argument from equality operators
in halo exchange example.
- Fixes equality operators in example
=> Remove an extra template argument

test/functional/forall/atomic-basic/tests/test-forall-atomic-basic.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceBitAnd.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceBitOr.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMax.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMaxLoc.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMin.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMinLoc.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceSum.hpp
- This PR enhances the basic forall-reduction functional tests to include all basic segment types we support. Specifically, tests that use range-stride and list segments have been added to tests for all reduction types.
=> Reduce segment test

test/functional/kernel/reduce-loc/test-kernel-reduceloc.cpp.in
- This PR is a task
- Adds seq-loop policies to CUDA, HIP, and CPU reduce-loc kernel tests. This seems to increase XL OpenMP compilation time by a couple minutes, but still finishes in under 10 minutes.
=> Update kernel reduce loc tests.

examples/red-black-gauss-seidel.cpp, scripts/lc-builds/blueos_clang11.0.0.sh, scripts/lc-builds/blueos_clang11.0.0_omptarget.sh, test/functional/forall/atomic-view/tests/test-forall-AtomicMultiView.hpp
- This PR fixes some compilation issues that arise when using clang11 compilers. It also add some build scripts.
Note that there are still other (mostly linking) issues, but this fixes the most obvious ones.
=> Fix compile issues for clang11 builds.

CMakeLists.txt, cmake/SetupPackages.cmake
This PR is a bugfix, and exports targets for third-party dependencies provided by BLT (e.g. CUDA and HIP) - this allows non-BLT projects to use the imported RAJA target.
=> Install targets for thirdparty exports

.github/PULL_REQUEST_TEMPLATE.md
- This PR removes the note about the gitlab CI in the PR template since it's no longer needed to initiate the CI tests.
=> removing note about gitlab CI

include/RAJA/util/TypeConvert.hpp
Remove volatile from the reintepret_cast in the non-volatile version of
the type conversion function used in the raja atomics.
This fixes a performance issue with hip where the value was written
to the stack during type conversion.
- This PR is something else
- Modifies RAJA::reinterp_A_as_B(non-volatile) to remove volatile in the reinterpret_cast
- Fixes issue where hip writes values to the stack
=> Remove volatile from non-volatile type conversion

test/functional/kernel/nested-loop/CMakeLists.txt
- It fixes compiler errors from a missing cmake variable needed in some generated OpenMP Target cpp test files.
=> Fixing omp-target cmake test bug

scripts/lc-builds/blueos_nvcc_clang.sh, scripts/lc-builds/blueos_nvcc_gcc.sh, scripts/lc-builds/blueos_nvcc_xl.sh, scripts/lc-builds/toss3_hipcc.sh
- This PR adds an arg to some of the build scripts to specify the cuda compute architecture.
@MrBurmark is this what you had in mind?
I'm not sure if it makes sense to have a default case for these scripts if no args are provided. Any thoughts on this?
=> Add arg to specify CUDA compute arch.

.gitlab/corona-jobs.yml
This PR is a  bugfix for hip versions in ci testing. Corona tests should no longer fail! (Using versions 4.0 and 4.1 now)
=> hip ci version updates

.gitlab/corona-jobs.yml, include/RAJA/policy/cuda/teams.hpp, include/RAJA/policy/hip/teams.hpp, test/functional/teams/tests/test-teams-BasicShared.hpp, test/include/RAJA_test-teams-execpol.hpp
This PR modifies kernel launches on Teams so they may run on the CAMP default stream.
Future work will expand the interface to users may pass in a resource object.
=> Enable RAJA Teams to run on CAMP default resource

docs/sphinx/user_guide/tutorial.rst, docs/sphinx/user_guide/tutorial/naming_kernels.rst
Adds a short documentation on using the kernel_name parameter in RAJA Team methods. 
Currently we only support NVTX tools. I noted in the docs that there may be some API changes as we integrate with other tools.
=> Docs for naming RAJA Teams based kernels

docs/sphinx/user_guide/feature/atomic.rst, docs/sphinx/user_guide/feature/policies.rst, docs/sphinx/user_guide/tutorial.rst, docs/sphinx/user_guide/tutorial/add_vectors.rst
- This PR is a documentation bugfix.
- We no longer support a default thread block size parameter. This PR corrects the parts of the user guide that referred to earlier versions of RAJA when we did support that.
Resolves https://github.com/LLNL/RAJA/issues/1072
=> Fixed documentation for cuda_exec policy.

.gitlab-ci.yml, .gitlab/ruby-jobs.yml, .gitlab/ruby-templates.yml, docs/sphinx/dev_guide/ci.rst
- This PR is improving the gitlab ci
- It moves the gitlab ci tests from quartz to ruby instead (less traffic)
=> Run gitlab ci jobs on ruby instead of quartz

.gitlab/ruby-templates.yml, scripts/gitlab/build_and_test.sh
- This PR is an improvement
- Reduces CPU resources requested during each build of the Gitlab CI. Hopefully build_and_test times will improve.
- Request max number of CPU resources per allocation, rather than specifying limited amounts.
- Discussed with @adrienbernede and @kab163. The strategy is to first throw more resources at the jobs, while restricting the build phases to fewer cores to allow more tasks to run in parallel. We would like the inherent scheduler to distribute the work for us, rather than maintaining a complicated set of scripts and dependencies. Failing that, we may need to sub-divide the current stages into more stages and jobs.
=> Improving Gitlab CI performance.

examples/raja-teams.cpp, examples/teams_matrix-multiply.cpp, examples/teams_reductions.cpp
Folks, I noticed that with the transition of running team kernels on the CAMP default stream we introduced some failing examples. This occurs since our examples draw from the CUDA default stream (different than CAMP default stream). 
This PR adds a fix by adding synchronization after kernels.
=> Fix synchronization in examples

CMakeLists.txt
This PR is a build system improvement.
It does the following:
* Checks the CUDA and HIP version numbers against the minimums given in the documentation.
* Fixes #947
=> changes to CMake to check the versions of cuda and hip

include/RAJA/pattern/kernel/For.hpp, include/RAJA/policy/loop/forall.hpp, include/RAJA/policy/openmp_target/policy.hpp, include/RAJA/policy/sequential/forall.hpp, include/RAJA/util/resource.hpp
- This PR is a bug fix 
- Fixes #1092 and #1093 
- Fixes resource selection process for nested kernels.
The existence of these bugs also suggests there should be more CI/CD testing of OpenMP target offloading, as without these changes, OpenMP target offloading tests do not build at all. 
Thank you @trws for the help figuring out what was causing the issues!
=> OpenMP Target Resource Fixes

include/RAJA/policy/hip/policy.hpp
Forgot to add this policy for unordered hip workgroups or it was removed by accident.
- Fixes missing policy
=> Add missing hip workgroup unordered policy

.gitmodules, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefAdd.hpp, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefCAS.hpp, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefLoadStore.hpp, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefLogical.hpp, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefMinMax.hpp, test/functional/forall/atomic-ref/tests/test-forall-AtomicRefSub.hpp, test/functional/forall/atomic-view/tests/test-forall-AtomicView.hpp, test/include/RAJA_test-workgroup.hpp, test/unit/algorithm/tests/test-algorithm-sort-utils.hpp
- CAMP https://github.com/LLNL/camp/pull/73 makes the resource default to Device allocations. This PR fixes the atomic-ref tests to use Device memory, and temporarily uses Managed memory to shore up the WorkGroup and Sort tests.
- Updates CAMP to v0.2.1.
=> Fix CUDA tests to align with CAMP resource default Device memory.

cmake/SetupRajaConfig.cmake, include/RAJA/config.hpp.in
Remove the cmake option RAJA_ENABLE_HIP_INDIRECT_FUNCTION_CALL and choose to define it in the config based on the hip version instead.
- Adds automatic hip device call support detection
I chose to remove the cmake option RAJA_ENABLE_HIP_INDIRECT_FUNCTION_CALL in favor of checking and defining/not defining the var in the config because my original intention was to not allow this to be configurable. It is also possible to make this user configurable in cmake with the default checking the compiler version in cmake to set RAJA_ENABLE_HIP_INDIRECT_FUNCTION_CALL appropriately.
=> Enable hip device functions automatically

test/functional/kernel/CMakeLists.txt, test/functional/kernel/basic-single-icount-loop/CMakeLists.txt, test/functional/kernel/basic-single-icount-loop/test-kernel-basic-single-icount-loop.cpp.in, test/functional/kernel/basic-single-icount-loop/tests/basic-single-icount-loop-impl.hpp, test/functional/kernel/basic-single-icount-loop/tests/test-kernel-basic-single-icount-loop-segments.hpp
- This PR is a part of the test refactor
- Adds basic ForICount tests to the functional kernel test suite. 
- Tests Kernel ForICount across common exec policies and index types.
- Supports testing StronglyTyped types.
=> Adding basic ForICount Kernel testing.

README.md
- This PR is a feature.
- It updates the status badges on our GitHub project homepage to show what we are actually using.
=> Add azure and rtd build status badges. Remove travis badge.

.gitlab/lassen-jobs.yml, scripts/spack_packages/raja/package.py
- It removes some old code from our spack package that prevented our clang tests from building on Gitlab CI for lassen (you read that correctly...our tests were not building with clang on GItlab CI for lassen).
- It also updates versioned release info and fixes an issue with the project homepage URL
=> Fix spack package.

scripts/spack_packages/raja/package.py
- This PR removes a compiler option in our spack package that causes a bunch of compiler warnings when it is not a supported compiler option.
=> Remove compiler flag that causes a bunch of warning spew in Gitlab CI.

include/RAJA/util/StaticLayout.hpp
- This PR is a bugfix to #1033 
- Changes the false return to a 0 to avoid signed/unsigned type warnings.
=> StaticLayout Warning

include/RAJA/policy/loop/scan.hpp, include/RAJA/policy/sequential/scan.hpp, test/functional/scan/tests/test-scan-Exclusive.hpp, test/functional/scan/tests/test-scan-Inclusive.hpp
Fix exclusive scan with const-iterators
Also make loop and sequential implementations consistent.
- This PR is a bugfix and refactoring
- refactors loop scan implementation to match sequential where appropriate
- Fixes #1191
=> Fix exclusive scan with const-iterators

.gitlab-ci.yml
- This PR truns off gitlab ci for corona until it can be run
**Meanwhile, please run Hip tests manually on rznevada and note that you have done so in your PRs.**
=> Turn off corona ci until machine is back up

scripts/lc-builds/toss3_hipcc.sh
Unload the rocm module in the hip build script to avoid some
inconsistencies that appear if using the script while having
a rocm module loaded. Namely cmake will use the rocprim from
the rocm module because it searches the CMAKE_PREFIX environment
variable set by the module first.
- Fixes #1140
=> Improve hip build script

CMakeLists.txt, cmake/SetupPackages.cmake
Looks like there were some changes to cmake that were not propagated to the ROCTX configuration. 
This PR propagates those changes.
=> Fix roctx cmake configuration

benchmark/host-device-lambda-benchmark.cpp
- It pulls in the correct google benchmark header so our benchmark code compiles. The issue may be due to a change in version of google benchmark since the code was originally written.
=> Pull in correct header file

examples/tut_offset-layout.cpp, exercises/tutorial_halfday/ex6_stencil-offset-layout.cpp, exercises/tutorial_halfday/ex6_stencil-offset-layout_solution.cpp, include/RAJA/util/OffsetLayout.hpp, test/functional/forall/segment-view/tests/test-forall-RangeSegment2DView.hpp, test/functional/kernel/nested-loop-view-types/tests/test-kernel-nested-loop-OffsetView2D.hpp, test/functional/kernel/nested-loop-view-types/tests/test-kernel-nested-loop-OffsetView3D.hpp, test/functional/kernel/nested-loop-view-types/tests/test-kernel-nested-loop-PermutedOffsetView2D.hpp, test/functional/kernel/nested-loop-view-types/tests/test-kernel-nested-loop-PermutedOffsetView3D.hpp, test/unit/view-layout/test-makelayout.cpp, test/unit/view-layout/test-multiview.cpp, test/unit/view-layout/test-standard-layout.cpp, test/unit/view-layout/test-typedview.cpp
Change OffsetLayout constructor and maker functions to take begin, end where end is excluded instead of first, last where last is included.
This also fixes the tests, examples, and exercies. Note that some tests were not changed because were previously wrong and assumed the [begin, end) behavior and the out of bounds accesses didn't happen to cause failures.
- Fixes #1173
=> Fix OffsetLayout Constructor

include/RAJA/config.hpp.in, include/RAJA/pattern/tensor/internal/VectorRegisterImpl.hpp, include/RAJA/policy/tensor/arch/avx/avx_int32.hpp, include/RAJA/policy/tensor/arch/avx/avx_int64.hpp, test/include/RAJA_gtest.hpp
- This PR is a bugfix for gcc
- Fixes RAJA_UNROLL to not break on gcc, and also work correctly with CUDA
- Fixes SIMD intrinsics to properly work for in32 and in64 with GCC
- Removed a warning being emitted from the RAJA_gtest.hpp file
=> Fixed warnings, simd intrinsics, and unroll issues with gcc

include/RAJA/policy/tbb/scan.hpp
Use type of *out instead of *begin to avoid using const types in the implementation.
- Fixes tbb scan
=> Fix tbb scan

include/RAJA/config.hpp.in
Adds a companion UNROLL macro which lets users unroll for a fixed count. Used in the RAJA PerfSuite.
Companion PR: https://github.com/LLNL/RAJAPerf/pull/225
=> Add fixed count unroll macros 

include/RAJA/config.hpp.in
Need to undef RAJA_UNROLL_COUNT when inside a cuda kernel. This PR fixes a warning that comes up with clang + nvcc.
=> Fix bug for cuda + host unrolling

.gitlab/corona-jobs.yml, scripts/spack_packages/raja/package.py
This cleans up the HIP builds by correctly using the `CMAKE_HIP_ARCHITECTURES` variable.
=> Fix usage of amdgpu_target/CMAKE_HIP_ARCHITECTURES

.gitlab/lassen-jobs.yml, .gitlab/ruby-jobs.yml, cmake/SetupRajaOptions.cmake, docs/sphinx/user_guide/config_options.rst, docs/sphinx/user_guide/getting_started.rst
- Prior to this we were setting RAJA_ENABLE_OPENMP as a cached variable and also as a dependent option.
- The changes made here change the default for OpenMP to off. It must be enabled using a CMake option (i.e., -DENABLE_OPENMP=On). This is consistent with how we handle other back-ends and also allow folks to turn OpenMP off, if desired, which was broken before.
- User guide is also updated to relflect this change.
- Also, changed blueos clang builds to use regular clang and not clang-ibm. We have intermittent test failures with clang-ibm that I think are due to runtime issue(s).
Note: the test configurations all also changed to include multiple OpenMP enable/disable scenarios; described in this issue https://github.com/LLNL/RAJA/issues/1252
=> Change openmp default mechanism, so we can turn it off when needed

.gitlab/lassen-jobs.yml
- This PR pulls in the latest radiuss-spack-configs version of the submodule
- It also updates some of the GItlab CI builds on lassen
Note: the compiler specs in the radiuss-spack-configs repo require further updates. When that is done, we can update the compiler for Gitlab CI again in a new PR.
=> Update radiuss-space-configs submodule and Gitlab CI for lassen

.gitlab/corona-jobs.yml
This PR switches the CI jobs running on corona to use HIP 5.1.0
=> Switch to HIP 5.1.0 in CI

include/RAJA/policy/tensor/arch_impl.hpp
- This PR pulls a branch from a forked repo into the RAJA repo for review. The original PR is https://github.com/LLNL/RAJA/pull/1261
=> Guard tensor hip and cuda policy includes when not running on device

.gitlab/lassen-jobs.yml
- This PR is simply updates the version of CUDA used in Lassen Gitlab CI jobs to CUDA 11 (both 11.0.2 and 11.5.0 jobs)
=> Adding CUDA 11 jobs to Lassen CI

include/RAJA/internal/RAJAVec.hpp
- Includes `<algorithm>` for std::max
**This PR is from a fork. Please approve the one from a branch in our repo: https://github.com/LLNL/RAJA/pull/1285**
=> Add missing header

include/RAJA/util/CombiningAdapter.hpp
- This PR squashes warnings coming from CombiningAdapter tests about calling host function from host-device function.
=> Add warning suppression macro in a few spots to squash nvcc warnings

Dockerfile
- This PR is a bugfix:
- It sets LD_LIBRARY_PATH for llvm docker builds to expose libopenmp at runtime.
=> LD_LIBRARY_PATH for llvm containers.

cmake/SetupRajaOptions.cmake
- This PR reverses the logic for disabling vectorization features in a build. This makes the default 'On'. Users can still disable if they wish.
=> Enable vectorization by default.

cmake/SetupPackages.cmake, examples/resource-forall.cpp, include/RAJA/config.hpp.in, include/RAJA/policy/cuda/MemUtils_CUDA.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/hip.hpp, include/RAJA/policy/hip/MemUtils_HIP.hpp, include/RAJA/policy/hip/reduce.hpp, include/RAJA/policy/openmp/sort.hpp, include/RAJA/policy/sycl/MemUtils_SYCL.hpp, scripts/lc-builds/toss3_hipcc.sh, scripts/lc-builds/toss4_amdclang.sh, scripts/lc-builds/toss4_cce_hip.sh, src/MemUtils_CUDA.cpp, src/MemUtils_HIP.cpp, src/MemUtils_SYCL.cpp
- This PR fixes issue with _OPENMP not defined in rocm device compiler pass.
- It also fixes example so it builds when openmp and hip are both enabled.
=> OpenMP + HIP build

include/RAJA/pattern/params/forall.hpp, include/RAJA/policy/loop/forall.hpp, include/RAJA/policy/openmp/params/forall.hpp, include/RAJA/policy/openmp_target/forall.hpp, include/RAJA/policy/sequential/forall.hpp, include/RAJA/policy/simd/forall.hpp
- This PR is a fix
- Removes RAJA_EXPT_FORALL_WARN macro.
=> Remove RAJA_EXPT_FORALL_WARN macro.

include/RAJA/policy/tensor/arch/avx512/avx512_int64.hpp
- Fixes missing `||` operator in compiler intrinsic logic.
=> Missing OR operator in AVX compiler checking logic.

include/RAJA/policy/openmp_target/forall.hpp
- It fixes a typo in the new omp-target reduction clause
=> Reduction typo.

cmake/SetupPackages.cmake
- It exports the `roctx` target when `RAJA_ENABLE_ROCTX
- Fixes #1375
=> Exports `roctx` target when present

include/RAJA/policy/openmp_target/kernel/For.hpp
- Fixes an issue mentioned here https://github.com/LLNL/RAJAPerf/pull/276
=> Add missing forall_param_pack in statement For

include/RAJA/policy/cuda/forall.hpp, include/RAJA/policy/hip/forall.hpp
This improves performance of hip forall kernels.
- Adds better hip forall performance at the request of me
=> Use compile time blocksize in forall

include/RAJA/pattern/params/reducer.hpp
Fixes name conflicts reported with MFEM in: https://github.com/mfem/mfem/pull/3293
=> Replace DEVICE macro with using alias

docs/sphinx/user_guide/getting_started.rst, scripts/lc-builds/blueos_clang_omptarget.sh, scripts/lc-builds/blueos_xl_omptarget.sh
- This PR changes the way we pass openmp flags to the compiler for openmp target offload builds so they work with new cmake min required version.
@MrBurmark feel free to push other script changes to this PR/branch
=> Update build scripts to work with newer cmake version

test/unit/workgroup/CMakeLists.txt
- After consulting with @MrBurmark, these tests should be removed because the functionality for OpenMPTarget dispatching in WorkGroups is not yet implemented, and cause a compilation error due to lack of policies for them.
=> Remove OpenMPTarget tests for WorkGroup Dispatcher.

scripts/lc-builds/toss4_amdclang.sh, scripts/lc-builds/toss4_amdclang_asan.sh, scripts/lc-builds/toss4_cce_hip.sh
This should get into the December release.
- This PR is a bugfix, feature
- Fixes use of craycc vs modules
- Adds instructions to use fp64 atomics at the request of me
=> Minor toss4 hip script fixes

scripts/lc-builds/toss4_hipcc.sh
This PR adds a script to build with hipcc as a temporary work around for RAJA test failures from missing symbols when building with amdclang. Building with hipcc resolves the missing symbol runtime test errors.
=> adding building script for hipcc

include/RAJA/config.hpp.in, include/RAJA/pattern/WorkGroup/WorkStruct.hpp
This PR fixes missing symbol errors when using amdclang:
In pattern/WorkGroup/WorkStruct.hpp
```
template < typename Dispatcher_T >
using GenericWorkStruct = WorkStruct<alignof(std::max_align_t), Dispatcher_T>;
``` 
std::max_align_t assumes alignof(std::max_align_t) evaluates to identical constants on both the host and device however a recent change in the AMDGPU backend (https://reviews.llvm.org/D127771) updated the long double size to be 8 bytes on the device (previously 16 bytes on both host and device) causing a template mismatch during deduction/instantiation which only manifests when std::max_align_t is evaluated at runtime.
Would like some input from @MrBurmark @rhornung67 @artv3 on implementation. Options I see are:
1. Add alignment as an overload and create a …
=> Fix amdclang missing symbols

test/functional/kernel/nested-loop/CMakeLists.txt, test/functional/kernel/nested-loop/tests/nested-loop-MultiLambda-impl.hpp
The gpu policy ran two dependent nested loops in the same kernel.
This is a race condition so it now uses two kernels so one nested loop is done before the other.
This fixes a known failure with hip.
This was passing for cuda, but it also had the same race condition.
- Fixes #988
=> Fix MultiLambda GPU test

include/RAJA/pattern/launch/launch_core.hpp, include/RAJA/policy/cuda/launch.hpp, include/RAJA/policy/hip/launch.hpp, include/RAJA/policy/loop/launch.hpp, include/RAJA/policy/openmp/launch.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/util/resource.hpp
This is a first attempt at reducing the number of exec methods in the launch backend framework. Thought is we can keep the exec method that takes a resource and simply pass in a default when users do not specify one.
=> Reduce number of exec methods in launch backends

include/RAJA/pattern/detail/reduce.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/hip/reduce.hpp, include/RAJA/policy/openmp_target/reduce.hpp, include/RAJA/policy/sycl/reduce.hpp, test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceMax.hpp, test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceMaxLoc.hpp, test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceMin.hpp, test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceMinLoc.hpp, test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceSum.hpp
There was a problem with the cuda and hip minloc and maxloc reducers. If you called reset you would change the identity value leading to incorrect results in some cases. This was caused by accidentally calling a base class reset method that treated the initial location argument as the identity. This PR adds a reset method in the derived class that hides the base class method.
In addition the arguments to all reduce loc constructors and resets were inconsistent. They now all take an initial value and location and an identity value and location.
The forall segment multiple reduce tests had some duplication and some potential for error in places so I refactored those to reduce duplication and fixed some potential for errors like the test assumed that first would always be 0.
- This PR is a …
=> Fix cuda and hip reduceloc reset and make interface consistent

include/RAJA/pattern/tensor/TensorIndex.hpp, include/RAJA/pattern/tensor/internal/TensorRef.hpp, include/RAJA/pattern/tensor/internal/TensorTileExec.hpp
- This PR is a pre-emptive bugfix
- In here https://rzlc.llnl.gov/gitlab/deterministic-transport/NG/Ardra/-/merge_requests/354, a lexer is used to generate some code, while using RAJA. There is a `BEGIN` macro defined in the lexer's header file which incurs replacement within the RAJA headers as well, leading to strange compilation errors. While this error is not necessarily due to any inherent RAJA bug, I'm replacing some of the type declarations with commonly used names to avoid this sort of problem in the vectorization API in the future.
=> Change type declarations in vectorization to avoid macro overload.

include/RAJA/pattern/detail/reduce.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/hip/reduce.hpp, include/RAJA/policy/openmp_target/reduce.hpp, include/RAJA/policy/sycl/reduce.hpp, test/unit/reducer/tests/test-reducer-reset.hpp
Always require both a value and loc. Previously the loc was optional as it had a default value.
- This PR is a refactoring/bugfix
- Fixes #1424
=> Consistent Loc Reducer Reset Args

include/RAJA/policy/cuda/MemUtils_CUDA.hpp, include/RAJA/policy/hip/MemUtils_HIP.hpp
- This PR is a bugfix related to #1447 
- Stops `cudaInfo` and `hipInfo` from initializing `res` members with constructors that call out to CUDA/HIP APIs before the runtime is initialized.
=> Fixing RAJA RDC build

RELEASE_NOTES.md, include/RAJA/policy/cuda/MemUtils_CUDA.hpp
- This PR resolves merge conflicts with mergeback from main after v2022.10.5 patch release.
- This must be merged into develop before https://github.com/LLNL/RAJA/pull/1453 can be merged
=> resolve merge conflicts with v2022.10.5 mergeback from main

.gitlab-ci.yml, .gitlab/corona-build-and-test-extra.yml, .gitlab/custom-jobs-and-variables.yml, .gitlab/tioga-build-and-test-extra.yml
Working on moving RAJAPerf to RADIUSS Spack Config (RAD_SConf)
Here is the process, with the merge sequence:
- I created a PR in RAD_SConf with new RAJA_Perf package,
- I used @main as a base branch, which has new rocmcc, which will force us to update Radiuss Shared CI (RAD_SCI) to v2023.03.0rc
- I created a PR in RAJA with new RAD_SConf (with raja_perf package) and update [RAD_SCI@v2023.03.0rc] as well as CI local config
- I created a PR in RAJAPerf with new RAJA (with new RAD_SConf (with raja_perf package) an RAD_SCI) and removed local RAJA_Perf package and pointed uberenv at RAD_SConf/packages in RAJA tpl.
- I also update RAD_SCI and local CI config.
Once test pass:
- [DONE] Merge PR in RAD_SCI@main
- [DONE] Update PR in RAJA to point to new [RAD_SCI@main]
- [THIS] Merge PR in …
=> [WOPTIM] Udpate spack-configs and shared-ci for raja-perf and other improvements

README.md
Speed up Caliper installation by setting up external python installation in Radiuss Spack Configs.
=> [Woptim] External python in Spack configuration

include/RAJA/config.hpp.in
- RAJA_COMPILER_MSVC must be defined for all Windows builds (even if using a compiler other than MSVC)
- In the future, we may want to consider renaming and/or using a different macro
Addresses #1452
=> Fix Windows build issue

include/RAJA/util/macros.hpp
- The ABORT_OR_THROW function was not properly seg faulting in OpenMP Target regions. Now, it writes to address 0 to generate a seg fault on TOSS and BlueOS platforms.
- Unused arg warnings from previous code have been eliminated.
=> Fix not seg faulting in abort_or_throw in OpenMP Target

test/unit/reducer/test-reducer-constructors-cuda.cpp, test/unit/reducer/test-reducer-constructors-hip.cpp, test/unit/reducer/tests/test-reducer-constructors.hpp
- The basic reducer constructor test was not being compiled for the GPU due to lack of an instantiation of the test. This particular test should not be runnable on the GPU, but Gtest requires an implementation anyway. Hence, the implementation is empty.
- Should help resolve CI pipeline failures in https://github.com/LLNL/RAJA/pull/1434 and https://github.com/LLNL/RAJA/pull/1289.
=> Complete implementations of GPU basic reducer constructor test

.readthedocs.yml
- This PR fixes the RTD build failing [urllib3 error](https://readthedocs.org/projects/axom/builds/20566025/)
- Relevant stackoverflow: [link](https://stackoverflow.com/questions/76185542/trying-to-run-jupyter-notebook-on-macos-13-3-1-a-with-python-3-9-importerror)
Passing build here: https://raja.readthedocs.io/en/bugfix-rtd_urllib/
=> Fix RTD build

host-configs/lc-builds/toss4/clang_X.cmake, scripts/lc-builds/toss4_clang.sh
- This PR updates the BLT submodule to the v0.5.3 release. 
- Updates host-config file for clang build on TOSS3 so it works with the new BLT, which includes a newer version of Googletest that requires newer C++ standard library headers.
- Added TOSS4 clang build script.
=> Bump BLT to v0.5.3

include/RAJA/util/TypedViewBase.hpp, test/functional/kernel/tile-variants/tests/test-kernel-tile-Fixed2DSum.hpp, test/functional/tensor/matrix/tests/test-tensor-matrix-ET_MatrixMatrixMultiplyAdd.hpp, test/functional/tensor/vector/tests/test-tensor-vector-ForallVectorRef1d.hpp
- Fixes `TypedView` to allow strongly typed indices with basic Layouts, and StaticLayouts.
- Modifies some existing tests to use strongly typed indices. More thorough testing will be done after impending release.
=> Fixes and Initial Strongly Typed Index Tests for Vectorization API

.gitlab-ci.yml, .gitlab/corona-build-and-test-extra.yml, .gitlab/lassen-build-and-test-extra.yml, .gitlab/ruby-build-and-test-extra.yml, .gitlab/tioga-build-and-test-extra.yml, Dockerfile, RELEASE_NOTES.md, azure-pipelines.yml, cmake/SetupRajaOptions.cmake, include/RAJA/config.hpp.in, include/RAJA/policy/openmp/sort.hpp
- This PR alters CMake logic to allow users to control whether OpenMP task variants of internal algorithms are on or off.
- It also updates the RADIUSS Spack configs submodule to a branch where the OpenMP task option is exposed as a Spack variant. That submodule branch also updates RAJA version constraints after v2023.06.0 release.
=> Expose OpenMP task option

include/RAJA/policy/cuda/kernel/internal.hpp, include/RAJA/policy/hip/kernel/internal.hpp, test/functional/kernel/basic-fission-fusion-loop/tests/basic-fission-fusion-loop-impl.hpp, test/functional/kernel/conditional-fission-fusion-loop/tests/conditional-fission-fusion-loop-impl.hpp
These are seen with the hip compilers
- It does the following :
- Fixes warnings
=> Fix warnings from KernelDimensionCalculator

docs/sphinx/user_guide/feature/policies.rst, include/RAJA/policy/cuda/MemUtils_CUDA.hpp, include/RAJA/policy/cuda/kernel/CudaKernel.hpp, include/RAJA/policy/cuda/policy.hpp, include/RAJA/policy/hip/MemUtils_HIP.hpp, include/RAJA/policy/hip/kernel/HipKernel.hpp, include/RAJA/policy/hip/policy.hpp, test/include/RAJA_test-forall-execpol.hpp
Fix the compilation of the occupancy calculator and Use common types between the hip and cuda backends in the occupancy calculator and kernel policies and kernel launch helper routines.
- This PR is a refactoring, bugfix
- Modifies/refactors occupancy calcualtor and kernel policies and helpers
- Fixes Occupancy Calculator compilation in certain circumstances
=> Fix occupancy calculator and Use common types

include/RAJA/pattern/params/forall.hpp, include/RAJA/policy/cuda/forall.hpp, include/RAJA/policy/cuda/params/reduce.hpp, include/RAJA/policy/cuda/policy.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/hip/forall.hpp, include/RAJA/policy/hip/params/reduce.hpp, include/RAJA/policy/hip/policy.hpp, include/RAJA/policy/hip/reduce.hpp
- This PR is a feature and bugfix
- Fixes direct cuda/hipMalloc call and memory leaks
- Adds compile time block size optimization for new reducer interface at the request of myself
=> New Reducer GPU Indexing

.readthedocs.yml, docs/requirements.txt
- It updates base install requirements for RTD builds so they work. 
- Something changed on read the docs within the last week so that our doc builds were broken.
- @davidbeckingsale @kab163 umpire doc builds are failing similarly. you probably have to make a similar fix there.
The RTD docs for this PR branch are here: https://raja.readthedocs.io/en/task-rhornung67-fix-rtd/
=> Attempt to fix RTD build

include/RAJA/policy/hip/MemUtils_HIP.hpp
This improves performance because it can be cached on device
- This PR is a  feature
- Adds more speed at the request of me
=> Use coarse grained pinned memory with Hip

include/RAJA/policy/hip/policy.hpp
- This PR is a bugfix (in ROCm6.0 HIP runtime is removing HCC, NVCC symbols)
- Replace \_\_HIP_PLATFORM_HCC__ with \_\_HIP_PLATFORM_AMD__
- Replace \_\_HIP_PLATFORM_NVCC__ with \_\_HIP_PLATFORM_NVIDIA__
**PR to review and merge** is https://github.com/LLNL/RAJA/pull/1570
=> Change HIP_PLATFORM from HCC to AMD and NVCC to NVIDIA

cmake/RAJAMacros.cmake
Let the NUM_MPI_TASKS and NUM_OMP_THREADS options through the raja_add_test and raja_add_benchmark cmake macros so they can be passed to BLT.
This is intended to be used in https://github.com/LLNL/RAJAPerf/pull/332.
- This PR is a feature,
- Adds ability to use BLT's mpi testing feature at the request of me
=> Pass mpi option through raja_add_test

test/unit/workgroup/tests/test-workgroup-Enqueue-Multiple.hpp
Reduce number of reps and number of enqueues per rep to improve testing times.
This helps asan tests complete without timing out.
- Modifies/refactors Workgroup Enqueue Multiple Tests
=> Shorten Workgroup Enqueue Multiple Tests

docs/sphinx/user_guide/feature/view.rst, test/unit/view-layout/test-indexlayout.cpp
This PR is for documenting the IndexLayout.
=> added documentation for IndexLayout

include/RAJA/policy/cuda/policy.hpp
CUDA emits a warning when specifying min threads per block and not number of threads in launch bounds parameters. 
The warning is of the type: 
```
warning : .minnctapersm is ignored when neither .maxntid nor .reqntid is specified.
```
=> Adjust launch bounds default parameters to avoid emitting a warning

.gitlab-ci.yml, .gitlab/jobs/corona.yml, .gitlab/jobs/lassen.yml, .gitlab/jobs/poodle.yml, .gitlab/jobs/ruby.yml, .gitlab/jobs/tioga.yml
A branch pointing at RADIUSS Shared CI with fixes for the Draft PR filter.
=> [Woptim] draft filter fix

include/RAJA/policy/sycl/launch.hpp, scripts/lc-builds/corona_sycl.sh
- This PR is a refactoring?
- Updates to the SYCL 2020 API. Memory accessors have changed and were generating deprecation warnings.
- Requires similar CAMP update https://github.com/LLNL/camp/pull/147.
=> SYCL Warnings

include/RAJA/RAJA.hpp, include/RAJA/util/for_each.hpp, test/unit/algorithm/CMakeLists.txt, test/unit/algorithm/test-algorithm-util-for_each.cpp
This takes the capability in RAJAPerf to iterate over types in a camp::list and brings that here along with an implementation of std::for_each.
I plan to use this to manually test many types without going through gtest's mechanism for this.
- Adds "type iteration" at the request of me
=> Add for_each and for_each_type

docs/sphinx/user_guide/feature/policies.rst, include/RAJA/policy/sycl/launch.hpp, test/include/RAJA_test-launch-direct-teams-threads-1D-execpol.hpp, test/include/RAJA_test-launch-direct-teams-threads-3D-execpol.hpp, test/include/RAJA_test-launch-execpol.hpp, test/include/RAJA_test-launch-loop-teams-threads-1D-execpol.hpp, test/include/RAJA_test-launch-loop-teams-threads-3D-execpol.hpp, test/include/RAJA_test-launch-runtime-execpol.hpp
Sycl uses the outermost index as the fastest, this change enables consistency when using RAJA::launch with other device back ends.
For reference this page has a good description on thread indexing using sycl: 
https://www.intel.com/content/www/us/en/docs/dpcpp-compatibility-tool/developer-guide-reference/2023-2/cuda-and-sycl-programming-model-comparison.html
See the Thread Indexing section.
=> Swap ordering of thread configuration in Sycl

include/RAJA/util/math.hpp, test/unit/util/CMakeLists.txt, test/unit/util/test-math.cpp
- This PR is a bugfix, feature
- Fixes missing math tests
- Adds prev_pow2 at the request of me
=> Add another math method and test

include/RAJA/pattern/kernel/For.hpp, include/RAJA/pattern/kernel/internal/LoopData.hpp, include/RAJA/pattern/kernel/internal/LoopTypes.hpp, include/RAJA/pattern/kernel/internal/Template.hpp, include/RAJA/policy/sycl/forall.hpp, include/RAJA/policy/sycl/kernel/SyclKernel.hpp, include/RAJA/policy/sycl/kernel/internal.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/policy/sycl/policy.hpp, include/RAJA/policy/sycl/reduce.hpp, test/functional/forall/reduce-basic/CMakeLists.txt
- This PR eliminates the need to use the internal set/getQueue methods in some parts of RAJA SYCL support. 
- There is more work to be done, briefly described in https://github.com/LLNL/RAJA/issues/1658. 
- The content of this PR is required to enable correct asynchronous execution of RAJA Perf kernels that use the RAJA::kernel interface. The associated PR that adds many SYCL kernel variants to RAJA Perf is https://github.com/LLNL/RAJAPerf/pull/441.
Passing resources explicitly to kernel execution methods results in consistent SYCL resource/queue usage during execution of most kernels as a result. getQueue method calls have been removed in some places as a result. When a resource is not passed to a kernel execution method, the code can now properly acquire the default SYCL resource via …
=> Remove dependences on RAJA internal set/getQueue methods

include/RAJA/policy/atomic_builtin.hpp
- Modifies builtin atomics to use atomic loads to guarantee correctness
- Fixes the call to the short-circuiting test by passing the original type rather than the value reinterpreted as unsigned or unsigned long
- Refactors the atomic CAS in a loop operations for more code reuse (as well as a simpler implementation)
- Provide a slightly faster implementation when there is no option for short-circuiting
=> Builtin atomics fixes

.gitlab/custom-jobs-and-variables.yml, .gitlab/jobs/corona.yml, .gitlab/jobs/lassen.yml, .gitlab/jobs/poodle.yml, .gitlab/jobs/ruby.yml, .gitlab/jobs/tioga.yml, .uberenv_config.json, scripts/gitlab/build_and_test.sh
In this PR, we set the GitLab CI to push Spack built binaries (RAJA dependencies) to the builtin OCI container registry.
This required an update of Spack, RADIUSS Spack Configs and Uberenv.
=> Use GitLab container registry as a Spack build cache

include/RAJA/policy/openmp/atomic.hpp, include/RAJA/policy/sequential/atomic.hpp
- This PR is a feature and bugfix
- Adds OpenMP 5.1 implementations for atomicMin and  atomicMax
- Fixes logic error in sequential atomicDec
- Prefer operator< instead of operator>
- Cast literals to appropriate type
=> Add OpenMP 5.1 implementations for atomics

.gitlab-ci.yml
I needed to test that reporting CI statuses to github was still working.
I seized the opportunity to update RADIUSS Shared CI in RAJA.
=> Update RADIUSS Shared CI to fix allocation release job

.gitignore, include/RAJA/pattern/atomic.hpp, include/RAJA/policy/atomic_auto.hpp, include/RAJA/policy/atomic_builtin.hpp, include/RAJA/policy/cuda/atomic.hpp, include/RAJA/policy/desul/atomic.hpp, include/RAJA/policy/hip/atomic.hpp, include/RAJA/policy/openmp/atomic.hpp, include/RAJA/policy/sequential/atomic.hpp, include/RAJA/util/EnableIf.hpp, include/RAJA/util/TypeConvert.hpp
- Modifies hip and cuda generic atomic compare and swap algorithms to use atomic loads instead of relying on volatile
- Re-implements atomic loads in terms of builtin atomics for cuda and hip (so that the generic compare and swap functions can use it)
- Removes volatile qualifier in atomic function signatures
- Uses cuda::atomic_ref in newer versions of CUDA to back atomicLoad/Store
- Uses atomicAdd as a fallback for atomicSub in CUDA
- Refactors CUDA atomics to reduce duplicate code (now more closely matches the Hip atomic implementations)
- Removes checks where `__CUDA_ARCH__` is less than 350 since RAJA requires that as the minimum supported architecture anyway
=> Remove volatile from atomics

examples/launch-param-reductions.cpp, include/RAJA/policy/sycl/launch.hpp, test/functional/launch/reduce-params/CMakeLists.txt
This PR adds sycl reducer support to RAJA::launch 
Interesting error when using more than 151 work-items: 
terminate called after throwing an instance of 'sycl::_V1::exception'
what():  The implementation handling parallel_for with reduction requires work group size not bigger than 151
=> Support for sycl reducers in RAJA launch

include/RAJA/policy/cuda/params/kernel_name.hpp, include/RAJA/policy/hip/params/kernel_name.hpp
When not using ROCTX or NVTX we have to guard for an unused variable.
=> fix unused variable warning

include/RAJA/util/TypeConvert.hpp
Only the c version of memcpy is supported
in device code.
I'm not sure why this compiles in our tests.
- Fixes hip compile
=> Use c version of memcpy in device code

include/RAJA/policy/openmp/atomic.hpp
While working to switch our Azure CI testing over to GitHub Actions and move to newer compiler images, I found that the Intel 2024 compiler does not like the ternary operator with some OpenMP clauses. This fixes the compilation error. Interestingly, intel 2022 and intel 2023 on LC systems don't have the issue.
@adayton1 whether to merge this is mainly your call.
=> Fix compilation issue with intel-2024

test/functional/forall/multi-reduce-basic/tests/test-forall-basic-MultiReduce.hpp, test/functional/kernel/multi-reduce-nested/tests/test-kernel-nested-MultiReduce.hpp, test/functional/launch/multi-reduce-nested/tests/test-launch-nested-MultiReduce.hpp
This was causing tests on windows to fail.
It is undefined behavior to construct a uniform_int_distribution with min > max
- This PR is a bugfix,
- Fixes ub in multireduce tests
=> Fix ub in multireduce tests

.github/workflows/build.yml, Dockerfile, azure-pipelines.yml, include/RAJA/policy/cuda/launch.hpp
Launch is using the wrong global function with a fixed cuda policy when there are reducers.
- Fixes a potential performance issue
=> Use right launch function with fixed reduce policy

host-configs/lc-builds/toss4/clang_X_asan.cmake, host-configs/lc-builds/toss4/clang_X_ubsan.cmake, include/RAJA/policy/openmp/launch.hpp, scripts/lc-builds/toss4_clang_san.sh, scripts/lc-builds/toss4_icpc-classic.sh, scripts/lc-builds/toss4_icpx.sh
- Fixes memory leak in the Launch OpenMP backend. Memory leak was found via clang ASAN.
- Updates some Intel build scripts.
- Adds build script for clang's ASAN and UBSAN sanitizers on TOSS4. 
- Note: Does _not_ fix the OpenMP Launch reduction tests. Will iterate with LC on those.
=> Fix OpenMP Launch Mem Leak and Add Clang Sanitizer Build

examples/launch_reductions.cpp, include/RAJA/pattern/launch/launch_core.hpp
A few applications have expressed interest support for perfectly nested loops within RAJA launch. This PR will enable applications to try out 3-level perfectly nested loops in their code base. Based on feedback and needs we can then modify the API to address user needs.
=> Experimental support for perfectly nested loops in launch

include/RAJA/util/math.hpp
It was missing host device decoration.
- Fixes issue found by @tomstitt
=> Add host device to math util

README.md, docs/index.rst
Adds links to the raja portability suite tutorials
=> Add links to the raja portability suite tutorial

benchmark/CMakeLists.txt
Adds a missing guard to desul atomic benchmark.
=> Add desul atomic header guard under benchmark

scripts/lc-builds/corona_sycl.sh
- It fixes the CMake version in the SYCL build script. What was there does not exist on corona.
=> Fix CMake version

docs/sphinx/user_guide/feature/reduction.rst, examples/forall-param-reductions.cpp, examples/launch-param-reductions.cpp, include/RAJA/pattern/params/forall.hpp, include/RAJA/pattern/params/params_base.hpp, include/RAJA/pattern/params/reducer.hpp, include/RAJA/policy/cuda/params/reduce.hpp, include/RAJA/policy/cuda/reduce.hpp, include/RAJA/policy/hip/params/reduce.hpp, include/RAJA/policy/hip/reduce.hpp, include/RAJA/policy/openmp/params/reduce.hpp, include/RAJA/policy/openmp_target/params/reduce.hpp, include/RAJA/policy/sequential/params/reduce.hpp, include/RAJA/policy/sycl/params/reduce.hpp, include/RAJA/util/SoAPtr.hpp, scripts/lc-builds/corona_sycl.sh, test/functional/forall/reduce-basic/CMakeLists.txt, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceBitAnd.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceBitOr.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMax.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMaxLoc.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMaxLocAlt.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMin.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMinLoc.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMinLocAlt.hpp, test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceSum.hpp, test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceBitAnd.hpp, test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceMin.hpp, test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceSum.hpp
- This PR is a refactoring:
- Refactors new reduction interface to have consistent min/max/loc operator semantics.
- Introduces type safety to reduction operators.
- Interface will be changed to require passing in ValOp objects, as opposed to the old interface which used raw data types. Changes will be highlighted with a comparison chart soon.
- ValLoc now requires IndexType, and must be used within a ValOp, e.g. `ValOp<ValLoc<T,IndexType>, Op>`.
- Satisfies this request https://github.com/LLNL/RAJA/issues/1582.
Original interface:
```
int sum = 0;
int min = large_num;
RAJA::expt::ValLoc<T, RAJA::Index_type> minloc(large_num, -1);
RAJA::forall<seqpol>(host_res, range,
RAJA::expt::Reduce<RAJA::operators::plus>(&sum), …
```
=> New Reducer ValOp Interface

.github/workflows/build.yml, .gitlab/jobs/poodle.yml, .gitlab/jobs/ruby.yml, .uberenv_config.json, azure-pipelines.yml, scripts/gitlab/build_and_test.sh
This PR :
- migrates CARE and Caliper to CachedCMakePackage, reducing the gap with implementations found in llnl/radiuss-spack-configs.
- improves coherency in version constraints across RADIUSS packages.
- updates Spack.
⚠️  TODO Before Merge:
=> Update and sandardize implementation of packages, in sync with spack update

include/RAJA/policy/openmp_target/params/reduce.hpp, test/unit/multi_reducer/CMakeLists.txt
- This PR is a bugfix:
- Fixes typo in OpenMP Target new reducer.
- Turns off OpenMP Target tests with the multi-reducer, because that backend is not yet implemented.
=> Fixes for OpenMP Target 

.gitlab/jobs/lassen.yml, cmake/SetupRajaOptions.cmake, test/functional/forall/CombiningAdapter/CMakeLists.txt, test/functional/forall/atomic-ref/CMakeLists.txt, test/functional/forall/atomic-view/CMakeLists.txt, test/functional/forall/indexset-view/CMakeLists.txt, test/functional/forall/multi-reduce-basic/CMakeLists.txt, test/functional/forall/reduce-basic/CMakeLists.txt, test/functional/forall/reduce-multiple-indexset/CMakeLists.txt, test/functional/forall/reduce-multiple-segment/CMakeLists.txt, test/functional/forall/resource-indexset/CMakeLists.txt, test/functional/kernel/basic-fission-fusion-loop/CMakeLists.txt, test/functional/kernel/conditional-fission-fusion-loop/CMakeLists.txt, test/functional/kernel/multi-reduce-nested/CMakeLists.txt, test/functional/kernel/nested-loop-reducesum/CMakeLists.txt, test/functional/kernel/nested-loop-segment-types/CMakeLists.txt, test/functional/kernel/nested-loop/CMakeLists.txt, test/functional/kernel/single-loop-tile-icount-tcount/CMakeLists.txt, test/functional/kernel/tile-variants/CMakeLists.txt, test/functional/workgroup/CMakeLists.txt, test/integration/CMakeLists.txt, test/unit/algorithm/CMakeLists.txt, test/unit/indexing/CMakeLists.txt, test/unit/multi_reducer/CMakeLists.txt, test/unit/reducer/test-reducer-constructors-openmp-target.cpp
- This PR cleans up OpenMP Target testing by doing the following:
- It also adds a working GItLab CI test jobs for lassen.
- Several RAJA issues have been added to capture tasks for future work.
=> OpenMP Target Testing

scripts/lc-builds/corona_sycl.sh
- This PR removes the line that enables benchmarks in the corona SYCL build script. The dpcpp compiler does not support C++ standards less than 17 and the version of google mark that comes with BLT does not support C++17.
- Support for C++17 in google benchmark was added yesterday. 
- I made an issue for BLT to update, after which we can re-enable. https://github.com/LLNL/blt/issues/709
=> Don't enable google benchmark in corona build script.

CMakeLists.txt, include/RAJA/config.hpp.in, include/RAJA/pattern/kernel/InitLocalMem.hpp, include/RAJA/policy/hip/policy.hpp, include/RAJA/policy/tensor/arch/hip/hip_wave.hpp, include/RAJA/policy/tensor/arch/hip/traits.hpp, test/include/RAJA_test-tensor.hpp
This is a feature. It adds a configuration time control parameter for the default wave size. On AMD MI cards this is generally 64, however on Radeon (gaming) cards this is usually 32. These changes will require the user to know if the card is setup for Wave32 or Wave64.
I also added a fix for the dynamically sized memory allocation which seems to trigger a lot of warnings for ROCm 6.2.
On (date), we reviewed this PR.  We discussed the design ideas:
1. First idea or goal
2. Second idea
3. Third idea
This PR implements 1. and 3.  It leaves out 2. for the following reasons
- (impractical)
- (too big)
- (not a good idea anyway)
=> Adding Radeon support by controlling wave size

examples/memoryManager.hpp, exercises/memoryManager.hpp, include/RAJA/pattern/launch/launch_core.hpp, include/RAJA/policy/sycl/MemUtils_SYCL.hpp, include/RAJA/policy/sycl/forall.hpp, include/RAJA/policy/sycl/kernel/Conditional.hpp, include/RAJA/policy/sycl/kernel/For.hpp, include/RAJA/policy/sycl/kernel/ForICount.hpp, include/RAJA/policy/sycl/kernel/Lambda.hpp, include/RAJA/policy/sycl/kernel/SyclKernel.hpp, include/RAJA/policy/sycl/kernel/Tile.hpp, include/RAJA/policy/sycl/kernel/TileTCount.hpp, include/RAJA/policy/sycl/kernel/internal.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/policy/sycl/policy.hpp, include/RAJA/policy/sycl/reduce.hpp, src/MemUtils_SYCL.cpp
- This PR squashes a bunch of compiler warnings due to deprecated SYCL usage in camp and RAJA. 
- Note: this PR depends on changes in a camp branch. That needs to be merged and pulled in here before this can be merged.
=> Remove deprecated SYCL usage for newer compilers

examples/dynamic-forall.cpp, examples/resource-dynamic-forall.cpp, include/RAJA/pattern/forall.hpp, test/functional/dynamic_forall/resource-segment/tests/test-dynamic-forall-resource-RangeSegment.hpp, test/functional/dynamic_forall/segment/tests/test-dynamic-forall-RangeSegment.hpp
This PR adds support for the new reducer interface to dynamic forall and brings it out of experimental.
=> Add support for the new reducer interface to dynamic forall

scripts/lc-builds/corona_sycl.sh
- This PR is an update
- Updates Corona build script to reflect usage of the latest SYCL compiler, built with ROCM/6.0.2 and the hash from 11/5/2024.
=> Update Corona SYCL build to use new compiler with ROCM 6.0.2.

include/RAJA/pattern/kernel/InitLocalMem.hpp
Use dynamically allocated buffer instead of dynamically sized local array in kernel InitLocalMem.
This is a problem because it is not valid C++ and causes large warnings to be generated when compiling with hip.
- Fixes large warnings in some cases
=> Use dynamically allocated buffer instead of dynamically sized local array in kernel InitLocalMem

include/RAJA/policy/cuda/kernel/CudaKernel.hpp, include/RAJA/policy/cuda/kernel/For.hpp, include/RAJA/policy/cuda/kernel/Tile.hpp, include/RAJA/policy/cuda/kernel/internal.hpp, include/RAJA/policy/hip/kernel/For.hpp, include/RAJA/policy/hip/kernel/HipKernel.hpp, include/RAJA/policy/hip/kernel/Tile.hpp, include/RAJA/policy/hip/kernel/internal.hpp
Track which dimensions are active when calculating dimensions in kernel. This allows us to know that we have no work to do in some cases where there was ambiguity before and kernels were launched despite having no work.
- Fixes #1733
=> Fix kernel to not launch a kernel if there is no work

include/RAJA/pattern/params/forall.hpp, include/RAJA/pattern/params/reducer.hpp, include/RAJA/policy/cuda/forall.hpp, include/RAJA/policy/cuda/launch.hpp, include/RAJA/policy/cuda/params/kernel_name.hpp, include/RAJA/policy/cuda/params/reduce.hpp, include/RAJA/policy/hip/forall.hpp, include/RAJA/policy/hip/launch.hpp, include/RAJA/policy/hip/params/kernel_name.hpp, include/RAJA/policy/hip/params/reduce.hpp, include/RAJA/policy/openmp/launch.hpp, include/RAJA/policy/openmp/params/forall.hpp, include/RAJA/policy/openmp/params/kernel_name.hpp, include/RAJA/policy/openmp/params/reduce.hpp, include/RAJA/policy/openmp_target/forall.hpp, include/RAJA/policy/openmp_target/params/kernel_name.hpp, include/RAJA/policy/openmp_target/params/reduce.hpp, include/RAJA/policy/sequential/forall.hpp, include/RAJA/policy/sequential/launch.hpp, include/RAJA/policy/sequential/params/kernel_name.hpp, include/RAJA/policy/sequential/params/reduce.hpp, include/RAJA/policy/simd/forall.hpp, include/RAJA/policy/sycl/forall.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/policy/sycl/params/kernel_name.hpp, include/RAJA/policy/sycl/params/reduce.hpp, include/RAJA/util/macros.hpp
Prepend param_ to the init, combine, and resolve overloads used to implement the params interface.
This avoids having to make a call to a specific function in detail and should allow the interface to be more extensible. Perhaps even to the point of letting users add params that could look at things like the cuda/hip launch parameters.
Also pass the policy by value to avoid having to specifying the template parameter explicitly.
- refactors params to be more easily greppable and more extensible
=> Rename param implementation

include/RAJA/policy/hip/forall.hpp, include/RAJA/policy/simd/params/kernel_name.hpp, include/RAJA/policy/simd/params/reduce.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/util/macros.hpp
- This PR squashes compiler warnings when SYCL is enabled.
- It also runs clang-format on the code to pass that check
=> Squash unused arg/var warnings.

include/RAJA/policy/sycl/forall.hpp, include/RAJA/policy/sycl/kernel/Lambda.hpp, include/RAJA/policy/sycl/kernel/SyclKernel.hpp, include/RAJA/policy/sycl/kernel/internal.hpp, include/RAJA/policy/sycl/launch.hpp, include/RAJA/policy/sycl/reduce.hpp
- This PR does what the title says.
- As part of this, a camp branch is also pulled in with some changes there. There is a PR in camp to merge that branch into main: https://github.com/LLNL/camp/pull/166. RAJA will be updated to a camp release soon. The camp changes were pulled in here to make sure the warnings were silenced.
=> Squash compiler warnings that appear in various CI checks

cmake/SetupRajaOptions.cmake, include/RAJA/config.hpp.in, include/RAJA/policy/openmp/atomic.hpp
This PR enables a workaround for issue https://github.com/LLNL/RAJA/issues/1812.
=> Enable optional omp 5.1 atomic min/max

include/RAJA/config.hpp.in
Explores discussion in https://github.com/LLNL/RAJA/issues/1830
I've verified that this change does indeed remove the warnings seen in mfem mini apps performance ex1.
=> Attempt to fix pragma warnings

include/RAJA/util/zip.hpp
- This PR is a minor refactoring adding const to the the operator() for  the tuple first member comparator.
=> Make comparator operator() call const

cmake/SetupCompilers.cmake, docs/sphinx/user_guide/config_options.rst
* The CUDA language standard is hardcoded to c++17, preventing anyone from building with a newer language standard. This fix allows the user to specify CMAKE_CUDA_STANDARD, and if it is not specified, BLT will set it based on the value in BLT_CXX_STD.
* Also clarifies the docs about config options
=> Fix handling of the CUDA language standard
