LLNL/RAJA

- include/RAJA/ThreadUtils_CPU.hxx
- src/LockFreeIndexSetBuilders.cxx
- src/MemUtils_CPU.cxx
- src/ThreadUtils_CPU.cxx
This significantly speeds up both LULESH 1.0 and LULESH 2.0.
> Fix bug in MaxThreads computation.

- .travis.yml
As @rhornung67 noted in #55, the CI isn't actually running any tests.  This is a bandaid to get it to at least run the unit tests and check their output until the unit testing refactor drops.
Thoughts @rhornung67, @davidbeckingsale?
> bandaid to run tests with travis until #50 drops

- include/RAJA/exec-cilk/reduce_cilk.hxx
- include/RAJA/exec-cuda/MemUtils_CUDA.hxx
- include/RAJA/exec-cuda/reduce_cuda.hxx
- include/RAJA/exec-openmp/reduce_openmp.hxx
- include/RAJA/exec-sequential/reduce_sequential.hxx
- test/unit-tests/CPUtests/main-reduce.cxx
- test/unit-tests/GPUtests/ReduceMax.cxx
- test/unit-tests/GPUtests/ReduceMaxLoc.cxx
- test/unit-tests/GPUtests/ReduceMin.cxx
- test/unit-tests/GPUtests/ReduceMinLoc.cxx
- test/unit-tests/GPUtests/ReduceSum.cxx
> Added get member function to reductions; also formatting changes to files I touched

- include/RAJA/forall_generic.hxx
Addresses slowdown discussed by mail (hopefully).
> switch to unowned for temporary scoped listsegment objects

- include/RAJA/exec-cuda/forallN_cuda.hxx
- include/RAJA/exec-cuda/forall_cuda.hxx
- test/unit/gpu/Nested.cxx
- test/unit/gpu/Traversal.cxx
> Skip 0 length cuda launches.

- include/RAJA/operators.hxx
I compiled RAJA with  -DCMAKE_CXX_FLAGS="-Wall -pedantic -Werror -Wextra -Wold-style-cast" and resolved the issues found in header files.
> Change to ensure header files can be compiled with gcc -Wold-style-cast -Wall -pedantic -Wextra -Werror.

- include/RAJA/Timer.hxx
This makes it easy to use a single timer to time different things (useful in performance suite).
> Added reset method to timer classes

- include/RAJA/exec-cuda/scan_cuda.hxx
- include/RAJA/exec-openmp/scan_openmp.hxx
- include/RAJA/exec-sequential/scan_sequential.hxx
- include/RAJA/scan.hxx
- test/unit/cpu/test-scan.cxx
> Fix unnecessary init for inclusive scans

- include/RAJA/internal/type_traits.hpp
- include/RAJA/policy/cuda/forall.hpp
- include/RAJA/policy/cuda/policy.hpp
- test/include/data_storage.hxx
- test/unit/CMakeLists.txt
- test/unit/cpu/test-scan.cxx
- test/unit/gpu/test-scan.cxx
- test/unit/test-type-traits.cxx
@willkill07 @trws this is almost fixed, but the scan tests won't compile.
> Fixes for policy traits and CUDA

- include/RAJA/internal/Iterators.hpp
- test/unit/cpu/test-segments.cpp
- test/unit/cuda/test-nested-strided.cpp
Also ensured correctness with negative strides. Added CPU and GPU unit tests to cover issues.
I cleaned up the GPU unit test to be a little more clear and general.
This addresses https://github.com/LLNL/RAJA/issues/296
> Fixed RangeStrideSegment bug with CUDA

- examples/example-add-vectors.cpp
- examples/example-jacobi.cpp
- examples/example-matrix-multiply.cpp
- examples/example-wave.cpp
- include/RAJA/util/basic_mempool.hpp
- include/RAJA/util/mutex.hpp
- src/DepGraphNode.cpp
- test/unit/cpu/test-nested.cpp
- test/unit/test-layout.cpp
> Fixed several issues related to clang compiler warnings.

- include/RAJA/pattern/nested.hpp
- test/integration/chai/chai-nested.cpp
- test/unit/nested.cpp
@rhornung67 , I was wondering if this is what you had in mind?
> Hiding the camp namespace

- examples/example-jacobi.cpp
- include/RAJA/pattern/nested.hpp
- include/RAJA/policy/openmp.hpp
- include/RAJA/policy/openmp/nested.hpp
- test/unit/nested.cpp
Code collapses for 2 or 3 for loops using the #pragma omp collapse clause.
> OMP Collapse 

- include/RAJA/index/IndexValue.hpp
- include/RAJA/index/RangeSegment.hpp
- include/RAJA/internal/Iterators.hpp
- test/unit/cpu/test-segments.cpp
We didn't have any unit tests for this, so I've added some tests and fixed the code so it works.
> Fixed TypedRangeStideSegment to work with strongly typed indices

- appveyor.yml
This updates GoogleTest, so hopefully AppVeyor starts working.
> Bump BLT version

- include/RAJA/pattern/detail/reduce.hpp
- include/RAJA/pattern/forall.hpp
I found warnings when compiling with CUDA 9. This PR removes the warnings.
> CUDA 9 Warnings

- .travis.yml
- travis-data/docker/clang6/Dockerfile
> add clang 6 dockerfile and add to travis matrix

- include/camp/camp.hpp
- include/camp/concepts.hpp
- include/camp/list/list.hpp
- include/camp/number.hpp
- include/camp/number/if.hpp
- include/camp/size.hpp
fixes #453 
If someone has icc15 handy, maybe test this, but the aliases are deduplicated.
> deduplicate as_list alias and fix header include order

- include/RAJA/util/View.hpp
- test/unit/CMakeLists.txt
- test/unit/test-view.cpp
> Allow construction of const Views from their nonconst analogues.

- examples/ex-batched-matrix-multiply.cpp
- examples/ex-offset.cpp
New examples for RAJA documentation. 
Example 1. Batched matrix multiply with different data layouts. 
Example 2. five-cell stencil with RAJA offsets.
> Cleaned up new examples

- CMakeLists.txt
- cmake/RAJAMacros.cmake
- cmake/SetupPackages.cmake
> Fix integration with CHAI

- include/RAJA/pattern/detail/reduce.hpp
- include/RAJA/pattern/reduce.hpp
- include/RAJA/policy/cuda/reduce.hpp
- include/RAJA/policy/openmp_target/reduce.hpp
- include/RAJA/util/types.hpp
> Generalize index type for minloc and maxloc reductions

- include/RAJA/pattern/detail/reduce.hpp
- include/RAJA/pattern/reduce.hpp
- include/RAJA/policy/cuda/reduce.hpp
- include/RAJA/policy/openmp_target/reduce.hpp
- include/RAJA/util/types.hpp
Reverts LLNL/RAJA#549
The testing for nvcc failed to run, but returned success:
https://travis-ci.org/LLNL/RAJA/jobs/466216803
> Revert "Generalize index type for minloc and maxloc reductions"

- CMakeLists.txt
- include/RAJA/pattern/kernel/Hyperplane.hpp
Fixes compilation issue when using CHAI, and at least the RAJA::statement::Hyperplane... may have caused other issues as well.
> Fixes issue with CHAI + RAJA::kernel

- include/RAJA/index/IndexValue.hpp
- include/RAJA/index/RangeSegment.hpp
- include/RAJA/policy/cuda/kernel/ForICount.hpp
- include/RAJA/policy/cuda/kernel/Tile.hpp
Eliminated a bunch of cases that caused inadvertent conversions between 32 and 64 bit integers
> Fixed for cuda performance

- include/RAJA/policy/cuda/MemUtils_CUDA.hpp
- include/RAJA/policy/cuda/forall.hpp
- include/RAJA/policy/cuda/kernel/CudaKernel.hpp
- include/RAJA/policy/cuda/reduce.hpp
Use cudaLaunchKernel API instead of <<<>>>.
> Use cudaLaunchKernel

- include/RAJA/util/View.hpp
> Small fix to make Views work in openmp target kernels. 

- test/integration/chai/chai-nested.cpp
- test/integration/chai/chai-tests.cpp
> Update CHAI integration tests

- .travis.yml
See https://github.com/codecov/codecov-bash/issues/162 for details
> Fix CodeCov uploading

- host-configs/alcf-builds/theta_intel18_0.cmake
- scripts/alcf-builds/theta_intel18.sh
Script for KNL machine at Argonne.
> Script for theta

- docs/sphinx/user_guide/feature/policies.rst
[comment]: # (#################################################################)
[comment]: # (Copyright 2016-19, Lawrence Livermore National Security, LLC)
[comment]: # (and RAJA project contributors. See the RAJA/COPYRIGHT file)
[comment]: # (for details.)
[comment]: #
[comment]: # (# SPDX-License-Identifier: BSD-3-Clause)
[comment]: # (#################################################################)
- This PR adds documentation for lesser known kernel policies and statements.
> Additional docs for kernel statements and policies

- host-configs/lc-builds/blueos/nvcc_xl_2019_X.cmake
- test/unit/cuda/test-forall-view.cpp
- test/unit/cuda/test-forall.cpp
- test/unit/cuda/test-reduce-loc.cpp
- test/unit/cuda/test-reduce-max.cpp
- test/unit/cuda/test-reduce-min.cpp
- test/unit/cuda/test-reduce-randloc.cpp
- test/unit/cuda/test-reduce-sum.cpp
- test/unit/cuda/test-reduce-tupleloc.cpp
- test/unit/cuda/test-scan.cpp
- test/unit/cuda/test-synchronize.cpp
- test/unit/test-atomic-ref.hpp
- test/unit/test-atomic.cpp
- test/unit/test-kernel-lambda-args.cpp
- test/unit/test-sharedmem.cpp
Add CUDA error checks to tests for safety and consistency. Also removed extraneous nvcc+xl cmake option, which was causing compilation issues.
> Adding cudaErrchk to tests.

- README.md
- docs/sphinx/user_guide/feature/policies.rst
- This PR attempts to clarify execution policy documentation and provide additional details about usage. Please look it over here: 
https://raja.readthedocs.io/en/doc-improvements/feature/policies.html
and let me know if things are clear or still somewhat confusing.
> Doc improvements

- include/RAJA/util/Operators.hpp
- test/unit/util/CMakeLists.txt
- test/unit/util/test-operators.cpp
- This PR is a new unit test
- It does the following
- Adds unit tests for operators.
> Operator Unit Test

- exercises/tutorial_halfday/CMakeLists.txt
- exercises/tutorial_halfday/ex1_vector-addition.cpp
- exercises/tutorial_halfday/ex7_nested-loop-reorder.cpp
- exercises/tutorial_halfday/ex7_nested-loop-reorder_solution.cpp
- exercises/tutorial_halfday/ex8_tiled-matrix-transpose.cpp
- exercises/tutorial_halfday/ex8_tiled-matrix-transpose_solution.cpp
- exercises/tutorial_halfday/ex9_matrix-transpose-local-array.cpp
- exercises/tutorial_halfday/ex9_matrix-transpose-local-array_solution.cpp
- This PR added an exercise to the tutorial (nested loop reorder) to help make it easier to onboard folks to RAJA::kernel usage.
- The Powerpoint slides on Confluence have also been updated.
> Added a new tutorial example to ease the onboarding of RAJA::kernel.

- examples/pi-reduce_vs_atomic.cpp
- This PR fixes a bug in the RAJA-CUDA atomic variant of the pi approximation example.
- It also makes the HIP variants consistent with the others.
> Fix bug in pi approx example and make HIP versions consistent with others

- include/RAJA/util/Layout.hpp
- include/RAJA/util/OffsetLayout.hpp
Bugfix to address https://github.com/LLNL/RAJA/issues/711
> bugfix for bounds check

- exercises/tutorial_halfday/ex7_nested-loop-reorder.cpp
- exercises/tutorial_halfday/ex7_nested-loop-reorder_solution.cpp
- exercises/tutorial_halfday/ex8_tiled-matrix-transpose.cpp
- exercises/tutorial_halfday/ex8_tiled-matrix-transpose_solution.cpp
- exercises/tutorial_halfday/ex9_matrix-transpose-local-array.cpp
- exercises/tutorial_halfday/ex9_matrix-transpose-local-array_solution.cpp
- This PR is modifies the last two exercises in our tutorial to (hopefully) help ease participants into the mechanics of RAJA::kernell policies. Rather than throw too much complexity at participants at once, or give them everything so they don't need to think about the exercises, these changes should help them familiarize themselves with the concepts incrementally.
- Modifications to the tutorial slides to reflect these changes are in progress and will be available soon.
> Improve exercises

- include/RAJA/config.hpp.in
- share/raja/cmake/RAJA-config.cmake.in
- This PR exposes RAJA version number as #define constants and exports the version number as a CMake variable.
- Also pulls in latest camp with some improvements we want.
> Config fixes

- exercises/tutorial_halfday/ex9_matrix-transpose-local-array.cpp
- exercises/tutorial_halfday/ex9_matrix-transpose-local-array_solution.cpp
- This PR makes minor changes in example 9 of the tutorial so the code is clearer and easier to explain in our tutorial slides.  It does not change any code behavior.
> Make tile indexing clearer

- include/RAJA/util/StaticLayout.hpp
- This PR bumps camp submodule to latest camp master branch.
> Bump camp to pull in latest changes.

- test/unit/reducer/test-reducer-constructors-cuda.cpp
- test/unit/reducer/test-reducer-constructors-hip.cpp
- test/unit/reducer/test-reducer-constructors-openmp-target.cpp
- test/unit/reducer/test-reducer-constructors-openmp.cpp
- test/unit/reducer/test-reducer-constructors-seq.cpp
- test/unit/reducer/test-reducer-constructors-tbb.cpp
- test/unit/reducer/test-reducer-reset-cuda.cpp
- test/unit/reducer/test-reducer-reset-hip.cpp
- test/unit/reducer/test-reducer-reset-openmp.cpp
- test/unit/reducer/test-reducer-reset-seq.cpp
- test/unit/reducer/test-reducer-reset-tbb.cpp
- Eliminates warnings from using deprecated Google test CASE. Changed to SUITE.
> Change Google test CASE to SUITE.

- README.md
- Modifies README.md to update references to main branch
> Rename master to main in README.md

- examples/wave-eqn.cpp
Updates policies for wave equation example. 
Original PR: https://github.com/LLNL/RAJA/pull/788
> Update wave eq example

- host-configs/lc-builds/toss3/hip.cmake
- scripts/lc-builds/toss3_hipcc3.6.0.sh
Rename corona hip build script to be more general for toss3 hipcc builds.
Make hip build script and host config more like the existing scripts and host configs.
- This PR is a (refactoring, bugfix, feature, something else)
- Modifies/refactors (class or method) (how?)
- Fixes (issue number(s))
- Adds (specific feature) at the request of (project or person)
On (date), we reviewed this PR.  We discussed the design ideas:
1. First idea or goal
2. Second idea
3. Third idea
This PR implements 1. and 3.  It leaves out 2. for the following reasons
- (impractical)
- (too big)
- (not a good idea anyway)
> rename hip build script

- test/include/RAJA_test-workgroup.hpp
Use RAJA_ASSERT_OR_THROW to avoid warnings and
provide understandable error messages in workgroup test
allocators.
- Fixes warnings
> Avoid warning from workgroup test header

- examples/raja-teams.cpp
- include/RAJA/config.hpp.in
- include/RAJA/index/ListSegment.hpp
- include/RAJA/pattern/teams.hpp
- include/RAJA/pattern/teams/teams_core.hpp
- include/RAJA/policy/cuda.hpp
- include/RAJA/policy/cuda/policy.hpp
- include/RAJA/util/resource.hpp
- test/functional/teams/tests/test-teams-BasicShared.hpp
- This PR is a refactoring: 
Adds additional #ifdefs to enable using CUDA ENABLED RAJA to be used
to be used with packages who may or may not be compiling with nvcc.
> Using CUDA enabled RAJA with non nvcc compiled codes.

- include/RAJA/policy/openmp_target/kernel/Collapse.hpp
- include/RAJA/policy/openmp_target/kernel/For.hpp
- Fixes compilation of omp-target kernels for omp_target_parallel_for_exec and omp_target_parallel_collapse_exec
> [WIP] Fixing omp-target kernel compile

- share/raja/cmake/RAJA-config.cmake.in
- This PR fixes a comment in the RAJA config cmake file.
> Fix comment.

- scripts/lc-builds/blueos_clang10.0.1.sh
- scripts/lc-builds/blueos_clang10.0.1_omptarget.sh
- This PR fixes the path to the compiler for clang in blueos build scripts.
> Build script fix

- .gitlab-ci.yml
- Fixes an automatic triggering of chai which doesn't work right now. (Turn back on later - hence my added comment)
> turning off trigger for chai

- scripts/uberenv/packages/raja/package.py
- It fixes the corona gitlab CI build issues
> fixing corona gitlab ci build issues

- docs/sphinx/user_guide/feature/policies.rst
- include/RAJA/policy/cuda/kernel/CudaKernel.hpp
- test/old-tests/unit/test-kernel.cpp
- This PR pulls the branch from a PR submitted on a forked repo into the RAJA repo for CI testing and merging when approved. The original PR is: https://github.com/LLNL/RAJA/pull/1038
> Pr from fork/1038

- Dockerfile
- azure-pipelines.yml
- Adds sycl azure CI support.
This will need the new oneapi axom docker image to be pushed before it will run correctly.
> Sycl Azure CI

- examples/halo-exchange/CMakeLists.txt
- examples/halo-exchange/Item.cpp
- examples/halo-exchange/Item.hpp
- examples/halo-exchange/Point.cpp
- examples/halo-exchange/Point.hpp
- examples/halo-exchange/SumTransaction.cpp
- examples/halo-exchange/SumTransaction.hpp
- examples/halo-exchange/halo-exchange.cpp
- This PR is a feature in example code
- Adds SumTransaction class in halo-exchange as an alternative to CopyTransaction
- Tests the results within the example driver
> Add SumTransaction option to halo-exchange example

- docs/sphinx/dev_guide/build_configurations.rst
- docs/sphinx/dev_guide/ci.rst
- docs/sphinx/dev_guide/contributing.rst
- docs/sphinx/dev_guide/release_process.rst
- This PR contains dev guide updates based on CI tool changes.
I addresses https://github.com/LLNL/RAJA/issues/1076
> Update dev guide based on CI tool changes.

- docs/sphinx/user_guide/tutorial/naming_kernels.rst
Adds docs for using kernel naming with AMD
> Add instructions for using kernel naming with AMD

- RELEASE_NOTES.md
- This PR adds a section to the release notes file for the recent minor patch release. This is needed to make all releases show up on the ECP E4S Doc Portal.
> Add section to release notes for recent patch release.

- .travis.yml
- cmake/SetupCompilers.cmake
- include/RAJA/config.hpp.in
- include/RAJA/internal/LegacyCompatibility.hpp
- include/RAJA/util/Layout.hpp
- include/RAJA/util/StaticLayout.hpp
This one is short and sweet for now.  It requires C++14 but uses no features yet.  I'll go through shortly and change a couple of things to remove their conditional compilation and start directly using 14 in a few places.  Mainly unconditionally use constexpr in some places and get rid of some of the unnecessary type calculations.
> require c++14

- CMakeLists.txt
- Dockerfile
- azure-pipelines.yml
May need slight additional tweaking, directly moves the camp submodule to the current HEAD commit on the 0.4.0 release branch of camp.
> bump camp version to 0.4.0

- examples/memoryManager.hpp
- examples/tut_dot-product.cpp
- include/RAJA/policy/sycl/forall.hpp
- include/RAJA/policy/sycl/kernel.hpp
- include/RAJA/policy/sycl/kernel/For.hpp
- include/RAJA/policy/sycl/kernel/SyclKernel.hpp
- include/RAJA/policy/sycl/kernel/Tile.hpp
- include/RAJA/policy/sycl/kernel/internal.hpp
- include/RAJA/policy/sycl/policy.hpp
- include/RAJA/policy/sycl/reduce.hpp
- include/RAJA/util/resource.hpp
- This PR adds support for kernel tiling policies in a SyclKernel
- It updates the internal naming scheme for the sycl group and local policies
**NOTE: The fork has been pulled into the RAJA repo. Please review and approve the PR: https://github.com/LLNL/RAJA/pull/1189**
> Sycl Kernel Tiling

- appveyor.yml
- include/RAJA/policy/tensor/arch/cuda/cuda_warp.hpp
- include/RAJA/policy/tensor/arch/hip/hip_wave.hpp
- This PR updates the camp submodule to v0.5.3, which fixes some CI build issues for RAJA.
- It also fixes some HIP compile warnings.
> Update camp to v0.5.3

- test/functional/util/test-CombiningAdapter-1D.cpp
- test/functional/util/test-CombiningAdapter-2D.cpp
- test/functional/util/test-CombiningAdapter-3D.cpp
> Fix warning in CombiningAdapter tests

- .gitlab-ci.yml
- scripts/make_local_branch_from_fork_pr.sh
- This PR also includes a minor change that improves the usage message for a script.
> Updates for corona CI

- azure-pipelines.yml
- test/unit/util/test-timer.cpp
- This PR is a bugfix...
- It enables tests of Windows and Mac builds on Azure
> Turn on Windows & Mac tests.

- .gitlab-ci.yml
- Dockerfile
- This PR is a evolution following corona switch from slurm to flux
> Adapt corona allocation to flux

- azure-pipelines.yml
- This PR is a refactor of our azure pipelines yaml file
> Azure Pipelines Cleanup

- include/RAJA/index/ListSegment.hpp
- include/RAJA/pattern/WorkGroup/Dispatcher.hpp
- Fixes #1328
- Fixes uninitialized data member warnings from ListSegment
> Fix some warnings

- host-configs/lc-builds/toss4/gcc_X.cmake
- host-configs/lc-builds/toss4/icpc_X.cmake
- host-configs/lc-builds/toss4/icpx_X.cmake
- include/RAJA/policy/tbb/forall.hpp
- scripts/lc-builds/toss3_icpc.sh
- scripts/lc-builds/toss4_gcc.sh
- scripts/lc-builds/toss4_icpc.sh
- scripts/lc-builds/toss4_icpx.sh
And fix privatizer usage in tbb forall.
- This PR is a bugfix, feature
- Fixes extra copy of body in tbb forall
- Adds toss4 build scripts at the request of me
> Add some scripts for toss4

- share/raja/cmake/RAJA-config.cmake.in
Address error reported in https://github.com/mfem/mfem/pull/3293#issuecomment-1321275729
> Adjust cmake target ordering, blt before camp

- include/RAJA/pattern/launch/launch_core.hpp
- test/include/RAJA_test-plugin-resource-launchpol.hpp
- test/integration/plugin/CMakeLists.txt
- test/integration/plugin/test-plugin-resource-launch.cpp.in
- test/integration/plugin/tests/test-plugin-resource-launch.hpp
Addresses https://github.com/LLNL/RAJA/pull/1393#discussion_r1037285613
> fix post launch call

- include/RAJA/pattern/params/reducer.hpp
Addresses: https://github.com/LLNL/RAJA/pull/1393#discussion_r1037288810
> move device_mem_pool_t to raja detail namespace

- RELEASE_NOTES.md
> Fix typo in release notes

- .gitlab/tioga-build-and-test-extra.yml
- This PR adds a HIP + OpenMP test for tioga
> Add hip+openmp test on tioga

- include/RAJA/pattern/tensor/TensorIndex.hpp
- include/RAJA/pattern/tensor/internal/TensorRef.hpp
- include/RAJA/pattern/tensor/internal/TensorTileExec.hpp
- include/RAJA/pattern/tensor/internal/VectorRegisterImpl.hpp
- This PR is a cleanup
- Adds clarifying comments, removes unnecessary code, and clarifies error output from StaticTensor work https://github.com/LLNL/RAJA/pull/1286.
> Clean up StaticTensor

- azure-pipelines.yml
- include/RAJA/config.hpp.in
- This PR pulls in changes from a PR on a forked repo: https://github.com/LLNL/RAJA/pull/1435
- Please review this PR to approve and merge
> try new logic for windows shared exports

- test/functional/dynamic_forall/segment/tests/test-dynamic-forall-RangeSegment.hpp
- test/include/RAJA_test-launch-teams_threads_1D_execpol.hpp
- This PR contains a couple of changes to squash compiler warnings.
> Squash some compiler warnings

- test/functional/launch/shared_mem/tests/test-launch-DynamicMem.hpp
- test/functional/launch/shared_mem/tests/test-launch-StaticMem.hpp
This PR contains a couple of changes to squash compiler warnings.
> Fixes for warnings in launch test 

- docs/sphinx/user_guide/feature/policies.rst
- This PR is for documentation
- Adds documentation at the request of lots of people
Documentation for this branch is enabled in read the docs for reviewer inspection. The relevant changes are here: https://raja.readthedocs.io/en/documentation-burmark1-kernelgpuglobalindexing/sphinx/user_guide/feature/policies.html
> Document kernel gpu indexing changes

- include/RAJA/util/TypedViewBase.hpp
- test/functional/kernel/hyperplane/tests/test-kernel-hyperplane-2D.hpp
- Fixes https://github.com/LLNL/RAJA/issues/1508 and https://github.com/LLNL/RAJA/issues/1509
> Fix Compilation Warnings in Vectorization and Hyperplane

- host-configs/lc-builds/toss4/icpc-classic_X.cmake
- scripts/lc-builds/toss4_icpc-classic.sh
- This PR modifies and add build scripts/host-config files for building with Intel classic compiler on TOSS3 and TOSS4 LC platforms.
> Update scripts to build witn Intel compilers

- include/RAJA/policy/cuda/MemUtils_CUDA.hpp
- include/RAJA/policy/cuda/WorkGroup/Dispatcher.hpp
- include/RAJA/policy/hip/MemUtils_HIP.hpp
- include/RAJA/policy/hip/WorkGroup/Dispatcher.hpp
> Avoid Using Stream 0

- include/RAJA/policy/hip/policy.hpp
- The title says it all. 
Original PR from fork of repo is here: https://github.com/LLNL/RAJA/pull/1568
Please review and approve this one to merge.
> Change HIP_PLATFORM from HCC to AMD and NVCC to NVIDIA

- docs/sphinx/user_guide/getting_started.rst
> Fix documentation typo

- docs/sphinx/user_guide/feature/reduction.rst
- examples/CMakeLists.txt
- examples/launch-param-reductions.cpp
- include/RAJA/pattern/launch/launch_core.hpp
- include/RAJA/policy/cuda/launch.hpp
- include/RAJA/policy/cuda/policy.hpp
- include/RAJA/policy/hip/launch.hpp
- include/RAJA/policy/hip/policy.hpp
- include/RAJA/policy/openmp/launch.hpp
- include/RAJA/policy/openmp/params/forall.hpp
- include/RAJA/policy/sequential/launch.hpp
- include/RAJA/policy/sycl/launch.hpp
- include/RAJA/util/macros.hpp
- test/functional/launch/CMakeLists.txt
- test/functional/launch/reduce-params/CMakeLists.txt
- test/functional/launch/reduce-params/test-launch-basic-param-expt-reduce.cpp.in
- test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceBitAnd.hpp
- test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceMin.hpp
- test/functional/launch/reduce-params/tests/test-launch-basic-param-expt-ReduceSum.hpp
Adds support for the new reducer framework within launch for all but the sycl backends.
> New reducers in launch

- .gitlab/custom-jobs-and-variables.yml
- .gitlab/jobs/corona.yml
- .gitlab/jobs/lassen.yml
- .gitlab/jobs/poodle.yml
- .gitlab/jobs/ruby.yml
- .gitlab/jobs/tioga.yml
- .gitlab/subscribed-pipelines.yml
- scripts/gitlab/build_and_test.sh
This branch hosts a Fix attempt from RADIUSS Spack Configs for RAJAPerf CI.
> [Woptim] rsc rajaperf mpiexec flag

- .gitlab/custom-jobs-and-variables.yml
- .gitlab/jobs/corona.yml
- .gitlab/jobs/lassen.yml
- .gitlab/jobs/poodle.yml
- .gitlab/jobs/ruby.yml
- .gitlab/jobs/tioga.yml
- CMakeLists.txt
- This PR updates all TPLs to what we want for the upcoming release.
- Note that not all TPLs have release tags yet. Those versions will be pulled in when they are available.
- This PR makes sure everything is working.
> Update TPLs to prepare for release

- .gitlab/jobs/corona.yml
- .gitlab/jobs/lassen.yml
- .gitlab/jobs/poodle.yml
- .gitlab/jobs/ruby.yml
- .gitlab/jobs/tioga.yml
- .uberenv_config.json
We update RADIUSS Spack Configs and Spack. The former for addition of latest release versions, the latter for a bugfix regarding compilers with very similar names (like we have in RSC).
> [Woptim] [WIP] Radiuss Spack Configs 2024 02 and newer Spack

- scripts/lc-builds/corona_sycl.sh
- It fixes a syntax error in a build script and makes the output easier to understand
> Fix syntax error in script

- .gitlab-ci.yml
- .gitlab/custom-jobs-and-variables.yml
This PR improves the CI by using the dedicated queue on tioga.
> Use new pci queue on tioga

- include/RAJA/policy/sycl/launch.hpp
Reopened this PR in hoped that it would have better luck with CI.
> Bugfixes for sycl 

- examples/dynamic_mat_transpose.cpp
- examples/resource-dynamic-forall.cpp
- examples/resource-runtime-launch.cpp
- include/RAJA/pattern/launch/launch_core.hpp
- include/RAJA/util/macros.hpp
- This PR is a bugfix/refactoring
- Addresses https://github.com/LLNL/RAJA/issues/1651
> Fix dynamic matrix transpose example

- .gitignore
- include/RAJA/pattern/atomic.hpp
- include/RAJA/policy/atomic_auto.hpp
- include/RAJA/policy/atomic_builtin.hpp
- include/RAJA/policy/cuda/atomic.hpp
- include/RAJA/policy/desul/atomic.hpp
- include/RAJA/policy/hip/atomic.hpp
- include/RAJA/policy/openmp/atomic.hpp
- include/RAJA/policy/sequential/atomic.hpp
- test/functional/forall/atomic-basic/tests/test-forall-atomic-basic-unsigned.hpp
- test/functional/forall/atomic-basic/tests/test-forall-atomic-basic.hpp
- Adds atomicLoad and atomicStore at the request of myself
- Adds *.swp files to gitignore list
> Add atomicLoad and atomicStore

- include/RAJA/pattern/kernel/Tile.hpp
- This PR is an attempt to fix an issue reported by Intel when attempting to build RAJA with a new version of their compiler. Described here https://github.com/LLNL/RAJA/issues/1656
- It appears to solve the issue with the example on Compiler Explorer cited in the reported issue.
Resolves https://github.com/LLNL/RAJA/issues/1656
> Fix clang compilation issue 

- test/CMakeLists.txt
- test/integration/CMakeLists.txt
- Fixes builds where RAJA is a submodule
> Fix builds with RAJA as submodule

- examples/forall_multi-reductions.cpp
- include/RAJA/util/for_each.hpp
> Add missing includes

- docs/sphinx/user_guide/feature/policies.rst
> minor spelling fix

- exercises/dot-product.cpp
- exercises/dot-product_solution.cpp
- exercises/vector-addition.cpp
- exercises/vector-addition_solution.cpp
- include/RAJA/policy/sycl/MemUtils_SYCL.hpp
- include/RAJA/policy/sycl/reduce.hpp
- src/MemUtils_SYCL.cpp
remove setQueue and getQueue from codebase, addressing #1658
> remove sycl::detail::setQueue and getQueue from codebase

- docs/conf.py
- This PR is a companion PR for one submitted on a fork of the RAJA repo: https://github.com/LLNL/RAJA/pull/1719
- This is needed to get all required CI checks to run.
> add sphinx jquery extension to fix read the docs search

- README.md
- docs/sphinx/user_guide/getting_started.rst
- docs/sphinx/user_guide/tutorial.rst
#Summary
Users find looking at RAJA Perf as a source of RAJA usage examples instructive. Hopefully, these modest changes will help them navigate to that project.
> Add refs and links to RAJA Perf and a couple other updates.

- docs/sphinx/dev_guide/build_configurations.rst
- docs/sphinx/dev_guide/ci.rst
- docs/sphinx/dev_guide/ci_tasks.rst
- docs/sphinx/dev_guide/contributing.rst
- This PR updates Dev Guide documentation to describe or CI workflows for Azure and GitHub Actions which were recently modified.
The generated RTD documentation for this PR branch is here: https://raja.readthedocs.io/en/task-rhornung67-devguide-update/sphinx/dev_guide/index.html
> Updated Dev Guide to describe current CI workflows

- include/RAJA/policy/atomic_builtin.hpp
> Builtin atomic fixes for 32 bit windows

- test/functional/kernel/basic-single-loop/test-kernel-basic-single-loop.cpp.in
- This PR turns off policy that is failing in GitLab CI for OpenMP target.
- Issue created to track and investigate further: https://github.com/LLNL/RAJA/issues/1781
> Comment out exec policy that is failing. 

- include/RAJA/pattern/params/forall.hpp
Addresses https://github.com/LLNL/RAJA/issues/1822
> Suppress warnings in kernel_naming helpers

- include/RAJA/pattern/params/forall.hpp
This PR fixes a build issue found in an application code.
> add missing host device on combine calls

- include/RAJA/policy/openmp/params/forall.hpp
- include/RAJA/policy/sycl/forall.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceBitAnd.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceBitOr.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMax.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMaxLoc.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMin.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceMinLoc.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-ReduceSum.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceBitAnd.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceBitOr.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMax.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMaxLoc.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMaxLocAlt.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMin.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMinLoc.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceMinLocAlt.hpp
- test/functional/forall/reduce-basic/tests/test-forall-basic-expt-ReduceSum.hpp
- test/functional/launch/reduce-basic/tests/test-launch-basic-ReduceBitAnd.hpp
- test/functional/launch/reduce-basic/tests/test-launch-basic-ReduceMin.hpp
- test/functional/launch/reduce-basic/tests/test-launch-basic-ReduceSum.hpp
This PR should to develop before going into the release candidate
> Support lambda capture reducer with kernel naming (to develop)

- cmake/SetupRajaOptions.cmake
- include/RAJA/config.hpp.in
- include/RAJA/policy/openmp/atomic.hpp
> optional omp 5.1 atomics (To develop)

- examples/plugin/caliper-plugin.cpp
Formats the clang caliper plug in file
> clang format caliper plug in

- .gitlab/jobs/lassen.yml
- Dockerfile
- include/RAJA/policy/openmp/params/reduce.hpp
- test/functional/kernel/hyperplane/CMakeLists.txt
- test/functional/kernel/hyperplane/test-kernel-hyperplane-2D.cpp.in
- test/functional/kernel/hyperplane/test-kernel-hyperplane-3D.cpp.in
- test/functional/kernel/hyperplane/tests/test-kernel-hyperplane-2D.hpp
- test/functional/kernel/hyperplane/tests/test-kernel-hyperplane-3D.hpp
- test/functional/kernel/reduce-params-multi-lambda/test-kernel-reduce-params-multi-lambda.cpp.in
- test/functional/kernel/reduce-params-multi-lambda/tests/test-kernel-reduce-params-multi-lambda.hpp
- test/functional/kernel/tile-icount-tcount-direct-unchecked/CMakeLists.txt
- test/functional/kernel/tile-icount-tcount-direct-unchecked/test-kernel-tile-count-direct-unchecked.cpp.in
- test/functional/kernel/tile-icount-tcount-direct-unchecked/tests/test-kernel-tile-ForICount-direct-unchecked.hpp
- test/functional/kernel/tile-icount-tcount-direct-unchecked/tests/test-kernel-tile-TileTCount-direct-unchecked.hpp
- test/functional/kernel/tile-icount-tcount-direct/CMakeLists.txt
- test/functional/kernel/tile-icount-tcount-direct/test-kernel-tile-count-direct.cpp.in
- test/functional/kernel/tile-icount-tcount-direct/tests/test-kernel-tile-ForICount-direct.hpp
- test/functional/kernel/tile-icount-tcount-direct/tests/test-kernel-tile-TileTCount-direct.hpp
- test/functional/kernel/tile-icount-tcount-loop/CMakeLists.txt
- test/functional/kernel/tile-icount-tcount-loop/test-kernel-tile-count-loop.cpp.in
- test/functional/kernel/tile-icount-tcount-loop/tests/test-kernel-tile-ForICount-loop.hpp
- test/functional/kernel/tile-icount-tcount-loop/tests/test-kernel-tile-TileTCount-loop.hpp
- test/include/RAJA_test-reduce-types.hpp
- test/include/RAJA_test-reducepol.hpp
This PR is currently aimed at the kernel valop feature branch https://github.com/LLNL/RAJA/pull/1799, but will be redirected at develop once this branch is merged
> test: add more comprehensive test coverage for kernel valop
